### ISSUE TITLE
Compoundlist.csv

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#100]
So, the vignette explains that the Compoundlist.csv needs 
The CSV file is required to have at least the following columns, which are used for
further processing and must be named correctly (but present in any order): \Rvar{ID, Name, SMILES, RT, CAS}. The columns \Rvar{ID} and \Rvar{SMILES} must be filled, the other columns
must be present in the file but do not need to be filled.

But, if you get this wrong, the error message doesn't mention anything about the CAS number!
Error in loadList("mix6.csv") : 
 Some columns are missing in the compound list. Needs at least ID, Name, SMILES, RT.

Also, the help for loadList doesn't mention what the vignette does. Add a sentence here?

**Comment by sneumann** [comment]
Erik fixed the error message explaining required columns in 8b9605e5c2111f28aef7ef18f264adbead16c9d2.
What needs to be added to manpage/vignette is still unclear.

**Comment by schymane** [comment]
The vignette has ~1 paragraph explaining what the compound list should look like.
Can you add the most important details to the help for loadList? E.g., the required and optional columns. Copy/paste from vignette is good
