### ISSUE TITLE
UAthens data & mzR

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#102]
> w <- msmsRead(w, files = fileList, cpdids = cpdidList,
               readMethod = "mzR", mode="pH", useRtLimit=TRUE)
  |                                                                                               |                                                                                       |   0%
Error in `colnames<-`(`*tmp*`, value = c("mz", "int")) : 
  'names' attribute [2] must be the same length as the vector [0]
In addition: Warning message:
In is.na(headerCache) :
  is.na() applied to non-(list or vector) of type 'NULL'

**Comment by ermueller** [comment]
Rminder for me to ask about this

**Comment by sneumann** [comment]
Move the "if (nrow(pplist) > 0) " check up just behind  "pplist <- ..."

**Comment by schymane** [comment]
Add a warning to the user that no precursor was detected and recommend to use setting fillPrecursorScan: TRUE
