### ISSUE TITLE
Clean up issue list/New labels

### ISSUE THREAD

**Issue by ermueller** [MassBank/RMassBank#107]
Hey everybody,

I just looked through the issue list and had (again) problems finding stuff. I looked for ways to sort out this problem and I thought we could use the labels (bug, enhancement, etc) more extensively to make it more readable and better organized.

It turns out: 

We can even create new labels for the issues!
It's described in this guide:
https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

which would be tremendously helpful to prioritize issues. This is - of course - open for discussion, but I would think 4 priority levels with these colours would be fitting.
"low" - green
"middle" - yellow
"high" - orange
"urgent" - red

It would immensely help and it would take maybe 20 minutes max to do this, of which just 5 would be creating these labels.

What do you guys think about this? I'd be very happy if we could spare some time for this.

**Comment by schymane** [comment]
Yup, I agree we should invest the time tomorrow.

**Comment by ermueller** [comment]
@meowcat , you would have to create the labels if that's ok. You're the only one who can, since it's your repo.

**Comment by meowcat** [comment]
Would these labels port to the MassBank dev repository once we move over there? Which I suggest we do soon anyway.

**Comment by schymane** [comment]
New label suggests:
"on hold"
"need test case"

**Comment by schymane** [comment]
"need unit test"

**Comment by schymane** [comment]
I have revamped the labels, added a few extras
 - urgent => immediate attention 
 - high priority => high on the to-do list, but not *immediate*
 - low priority => long term projects, 
 - wontfix is now "beyond scope" to make it sound better. 

Most other additions were in line with comments above. Erik, if you are happy with all that, feel free to close this issue, I have feedback from Steffen and Michele

**Comment by ermueller** [comment]
The new labels are great and make my life a little bit easier. I'm very happy, thanks for taking the time to do this.
