### ISSUE TITLE
Add SMILES check to loadList

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#111]
In answer to email from Erik just now:
Actually, this is something we've done "unofficially" in our code for ages at Step 1 of msmsWorkflow, but never built in to RMassBank, here's the snippet we've used - @ermueller feel free to use this or adjust as it suits you - you don't need to print the info as we did, maybe just use this to catch the errors and prompt the user to "Please check the SMILES for ID XXXX and reload list"?

files <- list.files(,"pos.mzML")
loadRmbSettings(settings_file)
loadList("E:/RMassBank/Compoundlist.csv")

For new standards: check smiles:

mode <- "pH"
smiles <- lapply(files, function(fileName) {
  # Find compound ID
  splitfn <- strsplit(fileName,'_')
  splitsfn <- splitfn[[1]]
  cpdID <- splitsfn[[length(splitsfn)-1]]
  print(cpdID)
  print(findSmiles(cpdID))
  # Retrieve spectrum data
  # check whether the mass can be found without problems
  mz <- findMz(cpdID, mode)
  gc()
  return(mz)
} )

w <- newMsmsWorkspace()
...and so on and so on....

**Comment by schymane** [comment]
this works well in 1.9.5.1 from Erik, but checks *all* substances in the list, which is time consuming if the list is long. Option would be to do the check after people have uploaded their files/compound IDs, to only check the compound IDs needed in the current run. 
Catches SMILES that are absent, but also those that cannot be parsed by CDK.

**Comment by schymane** [comment]
OK, what this doesn't catch is if the SMILES is missing for a given compound ID...which gets back to the suggestion to check the SMILES after the user has provided the IDs...

**Comment by schymane** [comment]
I'd like to add the "to close upon merging" label to this, but the only thing outstanding is catching the Compound IDs that are missing SMILES... - I guess this is also a quick check, right?

**Comment by ermueller** [comment]
Yeah, I'll add that check and then add the "close upon merging"-label.

**Comment by schymane** [comment]
done for msmsRead, to come for msmsWorkflow step=1, via msmsRead.
