### ISSUE TITLE
Add M+NH4+ to "mode" settings

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#112]
Currently:
# ' @param mode The processing mode (determines which ion/adduct is searched):
# ' \code{"pH", "pNa", "pM", "mH", "mM", "mFA"} for different ions
# ' ([M+H]+, [M+Na]+, [M]+, [M-H]-, [M]-, [M+FA]-).

The most major adduct missing is [M+NH4]+, which can be pretty intense and would be very nice to have.
More generally, do we add the possibility to have a user-defined adduct?

**Comment by ermueller** [comment]
Forgot something in documentation, will fix asap.

**Comment by schymane** [comment]
It seems something isn't quite right for pNH4 yet:

msmsWorkflow: Step 7. Reanalyze fail peaks for N2 + O
  |                                                                                                                                                                                          |                                                                                                                                                                                  |   0%Error in (function (custom_additions, mass, cpdID, counter, pb = NULL,  : 
  mode = "pNH4" not defined

**Comment by schymane** [comment]
I've added what should be the missing code and will test ...

**Comment by schymane** [comment]
This should probably have been closed long ago, latest error fixed with https://github.com/MassBank/RMassBank/commit/b027f652baa61e21e38a943d9b5c7cdbc34417b7
