### ISSUE TITLE
Fix mbWorkflow Step 1 error if absolutely no CAS numbers are present in Compound List

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#114]
This is the error that shouldn't happen but does :-)
If the CAS column is present in the compound list, but empty for all substances, we get e.g.:
>mb <- mbWorkflow(mb, infolist_path=infolist_path_csv_2)
>mbWorkflow: Step 1. Gather info from CTS
>101: smiles
>401: smiles
>403: smiles
>Error in if (dbcas != "") { : missing value where TRUE/FALSE needed

But, if a CAS number is entered for any one of the substances in the list, it works fine. 
More details in email sent to Erik today, 15:29.

**Comment by ermueller** [comment]
Can you pull from my github branch bioc2014 to see if it works now? 
I fixed it, but I don't actually see why the error should turn up later in the workflow and not in the beginning. I can also build the package if you like.

**Comment by uchem-massbank** [comment]
If you can send me a built version I can test it. Thanks!
