### ISSUE TITLE
Find workaround for ontoCAT by 2016

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#115]
Error in all 4 platforms, e.g. http://master.bioconductor.org/checkResults/devel/bioc-LATEST/RMassBank/zin2-checksrc.html we have 
- this is package ‘RMassBank’ version ‘1.9.1’
- checking package namespace information ... OK
- checking package dependencies ... ERROR
  Package suggested but not available: ‘ontoCAT’

The suggested packages are required for a complete check.
Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.

See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.
Status: 1 ERROR
See
  ‘/home/biocbuild/bbs-3.1-bioc/meat/RMassBank.Rcheck/00check.log’
for details.

**Comment by ermueller** [comment]
I really think that just changing the environment variable is a pretty unclean solution to this, and this problem isn't really caused by our side of things.

If we theoretically had a package with ontoCAT as an import or depends, then we couldn't just change an environment variable, could we? Maybe we should ask the ontocat-guys or the bioc-guys what's up with that? It's rather strange that ontoCAT isn't already installed on the bioc-zin2.

OntoCAT currently also has a check error on there, so maybe that's the problem?

**Comment by schymane** [comment]
Seems to be due to the ontoCAT package, contacted maintainers and BioD

**Comment by schymane** [comment]
ontoCAT has been deprecated. Suggest to use rols package:
http://www.bioconductor.org/packages/release/bioc/html/rols.html
But for the release, just disable the instrument checks for the moment and remove all references to ontoCAT.

**Comment by schymane** [comment]
rols will not cover what we need, it's only biological.

**Comment by schymane** [comment]
To ensure that your package is part of this release of Bioconductor you need to make sure that your package passes ''R CMD build'' and ''R CMD check''
- without error (by April 3, 2015) and
- without warning (by April 9, 2015).

**Comment by schymane** [comment]
Latest on ontoCAT from Natalja:
>For now I’ve removed particularly heavy functions out of the examples in Rd files and the check took me exactly 5 minutes.The updated version is submitted to svn. Hope it will pass Bioconductor checks.
>As to the java library support, I would take this responsibility for the next year but not longer. 

So, we need to watch the build reports and make sure our errors disappear - if so, a workaround is less urgent

**Comment by schymane** [comment]
We now have 1 yr to find a workaround for ontoCAT, renaming issue appropriately

**Comment by sneumann** [comment]
So, it's 2018 and ontoCAT removal is imminent, we should disable code relying on ontoCAT. Yours, Steffen

**Comment by schymane** [comment]
I'm reopening this because something is wrong and BioC are threatening to deprecate us now if we don't fix ... @sneumann @meowcat can you please look into it?
"The package has been failing since 05/16/18; If no action is taken over the next few weeks we will begin the deprecation process for your package."

http://bioconductor.org/checkResults/3.8/bioc-LATEST/RMassBank/malbec1-checksrc.html 

* checking package dependencies ... ERROR
Package suggested but not available: ‘ontoCAT’

The suggested packages are required for a complete check.
Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.

**Comment by sneumann** [comment]
Hi, I excised the code relying on ontoCat a while ago:
https://github.com/MassBank/RMassBank/pull/190/files
So probably this has not yet been pushed to BioC ?
Yours, Steffen

**Comment by schymane** [comment]
Ahha. Perhaps one has to be careful with commit messages closing issues then:
`Remove code depending on ontoCAT. Closes #115`
Because removing the code is part of the issue but the issue cannot be closed until it is pushed to BioC. But once closed it fell off the radar. 
Who will take care of that @meowcat @sneumann?
