### ISSUE TITLE
Tidy up gather Data (after BioC)

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#117]
Remove CID: in front of the (few) PubChem IDs where it turns up (e.g. CID:123456 should be 123456)
Remove duplicate names e.g. "Atrazine" and "atrazine"

**Comment by ermueller** [comment]
Duplicate names were removed, but this issues conflicts with #130 

Names were all caps for the last few versions, but that is fixed now.

**Comment by tsufz** [comment]
Obviously fixed.
