### ISSUE TITLE
CACTUS backup: OpenBabel or PubChem

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#121]
*NOTE: most of this has been done by email already, this is to make it "official" 
This is a new issue instead of resurrecting #109 or #90 which were similar...*

Current build errors likely due to CACTUS being down.
One workaround could be to use a web service to retrieve InChI Keys for SMILES instead of CACTUS when it's down. 
Alternative: OpenBabel is on all Bioconductor build machines and we could set-up RMB to be like ChemmineOB. Quote from Dan:
See the the README of ChemmineOB (http://bioconductor.org/packages/devel/bioc/readmes/ChemmineOB/README) section about "Compiling with OpenBabel in a non-standard location" and "compiling on windows". Your package should be set up to use the same environment variables to find openbabel source and libs. Note that this means that your end users will need openbabel installed as well, but I guess you are aware of this since you have SystemRequirements: OpenBabel in your DESCRIPTION file.

**Comment by schymane** [comment]
This is done, right?
Erik, do you want to add the "close upon merging" labels to everything that's been done (also other issues - seems like a few should be finished...). We can also count the "merging" as merging to the RMassBank github now, right?

**Comment by ermueller** [comment]
This has been long finished, forgot to close.
