### ISSUE TITLE
Changes to fillPrecursorScan = TRUE plus ExtendPpmLimit option

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#122]
A short summary of a long chat with Erik:
a) fillPrecursorScan = TRUE - we are bumping into more and more cases where we "fail" because this setting is FALSE and things would work if it's true (Athens autoMSMS was the latest). We agreed to basically leave this setting in the ini files for backward compatability, but ignore it, i.e. if fillPrecursorScan = FALSE and mzR fails, we would overwrite the setting and use fillPrecursorScan = TRUE because it usually works and it's easy to detect in the mzML if it's needed. Somehow the Athens data actually _failed_ before Erik's error catch with the "change the settings" message in this case ... and this solution seems somehow more elegant than yet another error message.
b) We're also bumping into more cases where the default settings (for nice Orbitrap data) do not hold and the workflow likewise fails (c.f. EDDP missing from Athens dataset because > 25 ppm precursor error). This is something we can also calculate, so we could force mzR to take the precursor closest to the actual mz (only _if_ we have UseRtLimit=TRUE(?) ) if mzR doesn't find anything within the ppm in the settings file. Thus, we'd have to couple revised precursor ppm limits with increasing the MSMS ppm limits as well (or we'd extract MSMS spectra and reject all the peaks as too inaccurate). 
Our final idea was 1) search for precursor within limits in settings 2) if not found, search for precursor with an upper cap of X ppm and print a warning message to the user so they are informed and 3) if no precursor within X ppm print a warning/error that there was no precursor detected within X ppm. Because there are also cases where the ppm is well known (e.g. our data) and also where the compound may genuinely not be detected, we'd add the option "ExtendPpmLimit=NUMBER" so that the user can choose to look beyond their settings ppm or not. 
@ermueller I'm not sure we should throw an error if it's outside the extended limit, just keep going without that compound ... this is the current behaviour, right?

**Comment by meowcat** [comment]
Unsure how much of this is still relevant:

@ 1) basically to autodetect if the fillPrecursorScan is needed is a good idea I think. Maybe a warning or message to the user could be put in place but even that is debatable :)

@ 2) I am not so convinced. 
a) I don't think it is good practice if the program starts to override the user's setting. Then what do we have the setting for?
b) I don't think the user should be encouraged to use RMassBank without looking through the configuration file and actually setting decent values
c) users will just ignore the warning messages and potentially produce and upload crap spectra...

**Comment by meowcat** [comment]
@schymane Is this still relevant? Imputing `fillPrecursorScan` I would consider. Any extended magic I am against.

**Comment by schymane** [comment]
I think things have moved on. Athens are contributing data successfully ... closing for now.
