### ISSUE TITLE
Retrieve MSMS by Scan Number

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#123]
Related to #122 but different enough for a new issue, Erik had the idea to add the option to retrieve by scan number rather than RT, if available. It could be useful and neat, but so far not so many real use cases. Thoughts?

**Comment by meowcat** [comment]
I personally would not do this, because I don't think that's what RMassBank should do... If the user has to do so much work and search out the scan number he wants, then we have failed providing them with a useful software :) Also if introduced it could potentially clutter the options too much...

**Comment by meowcat** [comment]
@schymane still of interest?

**Comment by schymane** [comment]
Let's close for now, can reopen if interest rekindles ...
