### ISSUE TITLE
Check settings are loaded in msmsRead

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#126]
A small bug: if one uses msmsRead for step 1 and forgets to load the settings, you get what appears to be an unrelated error:
> loadList("CMmix_cmpdList.csv")
> w <- newMsmsWorkspace()
> w <- msmsRead(w, filetable="file_IDs.csv",readMethod="mzR", mode="mH", useRtLimit=FALSE)
0%Error in mzlimits[[1]] : subscript out of bounds

If useRtLimit = TRUE, it dies at rtLimit instead ...
iirc, we have a catch and prompt for this in msmsWorkflow step=1, can a similar catch be build into msmsRead? 
If I load the settings this goes away but I get other problems ... I'll email Erik separately about those...

**Comment by ermueller** [comment]
This is solved with the refactor merge michele did, forgot to close
