### ISSUE TITLE
Change license default in settings to CC-BY or CC?

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#128]
Feedback from the hackathon: CC-BY-SA is quite difficult (SA makes things tricky).
Should we change our default to CC or CC-BY?

**Comment by sneumann** [comment]
CC-Zero is essentially PublicDomain, 
CC-BY can be fulfilled by saying sth. like "created with data from MassBank" 
I'd opt for CC-BY as default.

**Comment by tsufz** [comment]
Why makes what tricky? Some examples?

**Comment by uchem-massbank** [comment]
See e.g. http://opencontent.org/blog/archives/347

**Comment by schymane** [comment]
And http://oaspa.org/why-cc-by/

**Comment by tsufz** [comment]
well, I agree with CC BY

**Comment by tsufz** [comment]
Txs. Interestings blogs. I will talk to Masanori to get a general 
decision also from MassBank consortium and who is performing the 
relaunch of the records.

I can do for the UFZ hosted records as I will renew the database next week.



Am 21.07.2015 um 09:37 schrieb schymane:

**Comment by tsufz** [comment]
All MassBank EU hosted data are changed to CC BY license model. Except 
the literature spectra.

Am 24.07.2015 um 08:37 schrieb Tobias Schulze:
> Txs. Interestings blogs. I will talk to Masanori to get a general
> decision also from MassBank consortium and who is performing the
> relaunch of the records.
>
> I can do for the UFZ hosted records as I will renew the database next week.
>
>
>
> Am 21.07.2015 um 09:37 schrieb schymane:
>> And http://oaspa.org/why-cc-by/
>>
>> From: uchem-massbank [mailto:notifications@github.com]
>> Sent: Tuesday, 21 July 2015 9:33 AM
>> To: MassBank/RMassBank
>> Cc: Schymanski, Emma
>> Subject: Re: [RMassBank] Change license default in settings to CC-BY or
>> CC? (#128)
>>
>> See e.g. http://opencontent.org/blog/archives/347
>>
>>
>> From: Tobias Schulze [mailto:notifications@github.com]
>> Sent: Tuesday, 21 July 2015 9:29 AM
>> To: MassBank/RMassBank
>> Subject: Re: [RMassBank] Change license default in settings to CC-BY or
>> CC? (#128)
>>
>> Why makes what tricky? Some examples?
>>
>>
>> —
>> Reply to this email directly or view it on
>> GitHub<https://github.com/MassBank/RMassBank/issues/128#issuecomment-123198508>.
>>
>>
>>
>>
>> —
>> Reply to this email directly or view it on
>> GitHub<https://github.com/MassBank/RMassBank/issues/128#issuecomment-123199264>.
>>
>>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/MassBank/RMassBank/issues/128#issuecomment-123200315>.
>>
>>

-- 
Dr. Tobias Schulze

Wissenschaftler / Senior Scientist
Department Wirkungsorientierte Analytik / Effect-Directed Analysis

Helmholtz-Zentrum für Umweltforschung GmbH - UFZ
Helmholtz Centre for Environmental Research - UFZ
Permoserstraße 15 / 04318 Leipzig / Germany
phone +49 341 235 1083 / fax +49 341 235 451083
tobias.schulze@ufz.de / www.ufz.de

Sitz der Gesellschaft: Leipzig
Registergericht: Amtsgericht Leipzig, Handelsregister Nr. B 4703
Vorsitzender des Aufsichtsrats: MinDirig Wilfried Kraus
Wissenschaftlicher Geschäftsführer: Prof. Dr. Georg Teutsch
Administrativer Geschäftsführer: Dr. Heike Graßmann

Bitte denken Sie an die Umwelt bevor Sie diese E-Mail ausdrucken.
Please consider the environment before printing this e-mail.

**Comment by ermueller** [comment]
Fixedin my remote repo

**Comment by tsufz** [comment]
Solved in a67f6f6c5bdbab12aa16aa33c7d23a164ef6cc15.
