### ISSUE TITLE
Refactoring: XCMS-based and other "additional" reader functions

### ISSUE THREAD

**Issue by meowcat** [MassBank/RMassBank#129]
Hi @ermueller,
I finally proceeded with all the refactoring I wanted to do and a new structure for the msmsWorkspace and the spectra contained therein. However up to now I have not rewritten the XCMS-based functions in leMsMsRaw.R. 

They basically will need to be changed such that they now produce a RmbSpectraSet object. I found it not as complicated as it initially looked, you can refer to the code in findMsMsHR.mass... It mainly involves filling RmbSpectrum2 objects and a Spectrum1 object instead of making the dataframes that were used before.

Do you want to do this yourself or should I do it? I can do it, but maybe not in the next two weeks...

**Comment by ermueller** [comment]
I can do it, no problem. Is the "refactoring" branch the "official" branch now? If yes, could you put it into master?

**Comment by meowcat** [comment]
I intended to merge it into master once it is fully functional (including the XCMS functions) - if you guys prefer, I can also already do it now. Note - I already merged all your BioC2014 changes in.

**Comment by ermueller** [comment]
I'll merge the xcms functions and then we can push into master. That sounds much "cleaner" now that you say it.

**Comment by ermueller** [comment]
I'm still finding things that need to be fixed... This will still take a little bit.

**Comment by ermueller** [comment]
Hi Everyone, this is now finished!

Did you get my long progress mail? Tobias didn't get it, so I'm slightly concerned that the uni mailserver is having problems. I'll resend it if that is the case :)

**Comment by meowcat** [comment]
Hi Erik,

awesome! I'm looking forward to test running it :)

I didn't get a mail from you, so maybe it did really get lost in the depths of the Intertubes...
