### ISSUE TITLE
Random compound list capitalization

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#133]
All the records from one of Nikiforos' mixes had COMPOUND NAMES IN CAPITALS for no apparent reason, although they were not written as such in the compound list or infolist. Erik has the data, again this is for the record.

**Comment by ermueller** [comment]
I somehow slipped up with the build version I sent Nikiforos, because this error has been fixed already and was only in RMassBank for a few hours. I double checked, just to be sure, but it doesn't happen anymore.
