### ISSUE TITLE
Use case. Implement quickly!

### ISSUE THREAD

**Issue by meowcat** [MassBank/RMassBank#135]
use case:
- input file
- give me your features (mz / rt)
- i fish out the MS2 for it and export them as MSP or MGF

**Comment by meowcat** [comment]
MGF export is in MSnbase. Just use that (in a streamlined way)

**Comment by sneumann** [comment]
Excellent, MGF is what some identification tools might agree upon 
as input format, since they all have similar, but slightly different formats today. 
We would try MGF export for CASMI 2016 challenges.

**Comment by meowcat** [comment]
Will be done elsewhere
