### ISSUE TITLE
MGF, MSP export: general discussions

### ISSUE THREAD

**Issue by meowcat** [MassBank/RMassBank#138]
Hi,

as we all want to include MSP and MGF export, I think we need to declare more clearly what we want to do and how.

As a note, there is some support for MGF export in MSnbase, which RMassBank depends on anyway:
https://github.com/lgatto/MSnbase/blob/master/R/readWriteMgfData.R
(Works for MS2 out of the box, not for MS1, but it's an easy hack.)
Also MSP exists in more than one implementation, one of them is in OrgMassSpecR:
https://github.com/cran/OrgMassSpecR/blob/master/R/WriteMspFile.R

Both are rather basic and not metadata-rich.

Our main question though, is, if we want to purely write Spectrum objects to MSP/MGF or if we want to generate them as results of the mbWorkflow. Or even better, if we integrate the two processes (i.e. the workflow generates "information-rich spectra" and they can be "printed" to MSP, MGF or MassBank; but also alternatively "information-poor spectra" can be printed to either format, via the same mechanism.

**Comment by meowcat** [comment]
@sneumann @ermueller @schymane

**Comment by meowcat** [comment]
https://github.com/lgatto/MSnbase/issues/73 apparently fixes output of MS1 records.

**Comment by meowcat** [comment]
Find attached an example of a semi-information-rich MSP spectrum that was generated by Steve Stein when he converted our MassBank records to MSP. This metadata can be read by the NIST MS software, including the annotations.
[ketoprofen.zip](https://github.com/MassBank/RMassBank/files/66723/ketoprofen.zip)

I myself will communicated with Gert about how we should put metadata into MSP spectra in a unified way. Maybe also directly with Steve?

**Comment by meowcat** [comment]
Another preexisting MSP export for R: https://github.com/rwehrens/metaMS/blob/master/R/msp.R

**Comment by meowcat** [comment]
@ermueller @sneumann Look at the branch s4power. Among different S4 functionality additions there's also implementation of writeMgfData support for RmbSpectraSet class.
```writeMgfData(w@spectra[[22]], con="cbdz-me.mgf")``` for example, writes the parent and all children spectra into an MGF file. No filtering etc currently, which is a bit ugly for the parent spectrum in particular; but the new ```selectPeaks``` on RmbSpectrum2 and RmbSpectrum2List can be used for this.

**Comment by sneumann** [comment]
Hi, the s4power branch is missing a few fixes @ermueller added recently,
currently the Waters CASMI challenges cause 
````
msmsWorkflow: Step 4. Recalibrate m/z values in raw spectra
Error in `[.data.frame`(rcdata, , c("mzFound", "dppm", "mzCalc")) : 
````
I think the "No filtering etc" is fairly important, the MGF should contain the same peaks 
as the compiled MB record. 
Yours, Steffen

**Comment by meowcat** [comment]
> I think the "No filtering etc" is fairly important, the MGF should contain the same peaks
as the compiled MB record.

Yes, in the end. The current implementation is a very rudimentary first shot. I propose to modify the data structure in the mbWorkflow part a bit such that it becomes easier to export records in different formats ("finished" records into MSP and MGF, but also "raw" records). More on that in an upcoming issue or email.

Also, I want to merge the branch s4power as per #143.

**Comment by tsufz** [comment]
fixed in PR https://github.com/MassBank/RMassBank/pull/231
