### ISSUE TITLE
fix namespace issues in devel version

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#139]
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  es gibt kein Paket namens ‘MSnbase’
In addition: Warning message:
Paket ‘RMassBank’ wurde unter R Version 3.3.0 erstellt 
Error: Laden von Paket oder Namensraum für ‘RMassBank’ fehlgeschlagen

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  es gibt kein Paket namens ‘ProtGenerics’
In addition: Warning message:
Paket ‘RMassBank’ wurde unter R Version 3.3.0 erstellt 
Error: Laden von Paket oder Namensraum für ‘RMassBank’ fehlgeschlagen

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  es gibt kein Paket namens ‘BiocParallel’
In addition: Warning message:
Paket ‘RMassBank’ wurde unter R Version 3.3.0 erstellt 
Error: Laden von Paket oder Namensraum für ‘RMassBank’ fehlgeschlagen

How many more packages will I have to manually install???!!!!!
This cannot be for real .... and needs to be fixed.

**Comment by schymane** [comment]
> library(RMassBank)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  es gibt kein Paket namens ‘impute’
In addition: Warning messages:
1: Paket ‘RMassBank’ wurde unter R Version 3.3.0 erstellt 
2: In ext@test(object) : bytecode version mismatch; using eval
3: vorhergehender Import durch ‘mzR::peaks’ während des Ladens von ‘MSnbase’ ersetzt 
Error: Laden von Paket oder Namensraum für ‘RMassBank’ fehlgeschlagen

> library(RMassBank)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  es gibt kein Paket namens ‘ggplot2’
In addition: Warning messages:
1: Paket ‘RMassBank’ wurde unter R Version 3.3.0 erstellt 
2: vorhergehender Import durch ‘mzR::peaks’ während des Ladens von ‘MSnbase’ ersetzt 
Error: Laden von Paket oder Namensraum für ‘RMassBank’ fehlgeschlagen

**Comment by schymane** [comment]
> library(RMassBank)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  es gibt kein Paket namens ‘MALDIquant’
In addition: Warning messages:
1: Paket ‘RMassBank’ wurde unter R Version 3.3.0 erstellt 
2: vorhergehender Import durch ‘mzR::peaks’ während des Ladens von ‘MSnbase’ ersetzt 
3: vorhergehender Import durch ‘ggplot2::arrow’ während des Ladens von ‘MSnbase’ ersetzt 
4: vorhergehender Import durch ‘ggplot2::Position’ während des Ladens von ‘MSnbase’ ersetzt 
5: vorhergehender Import durch ‘ggplot2::unit’ während des Ladens von ‘MSnbase’ ersetzt 
Error: Laden von Paket oder Namensraum für ‘RMassBank’ fehlgeschlagen

**Comment by schymane** [comment]
and now a new error....
JEEZ that was worth it:

> library(RMassBank)
Error : Objekt ‘isEmpty’ ist nicht von 'namespace:S4Vectors' exportiert
In addition: Warning messages:
1: Paket ‘RMassBank’ wurde unter R Version 3.3.0 erstellt 
2: vorhergehender Import durch ‘mzR::peaks’ während des Ladens von ‘MSnbase’ ersetzt 
3: vorhergehender Import durch ‘ggplot2::arrow’ während des Ladens von ‘MSnbase’ ersetzt 
4: vorhergehender Import durch ‘ggplot2::Position’ während des Ladens von ‘MSnbase’ ersetzt 
5: vorhergehender Import durch ‘ggplot2::unit’ während des Ladens von ‘MSnbase’ ersetzt 
Error: Laden von Paket oder Namensraum für ‘RMassBank’ fehlgeschlagen

back to our old version...

**Comment by sneumann** [comment]
Hi,
Did you install msnbase with bioclite()?
That should take care of the dependencies.
Yours Steffen

---
I blame Android for the brevity and typos

**Comment by schymane** [comment]
BiocLite didn’t work either. Don’t ask me why, I don’t know.

**Comment by meowcat** [comment]
Hm... It works on my computer, where i did a fresh install of R-devel (keeping my old package library) and completely updated Bioconductor to Bioc-devel and all R(CRAN) packages to the newest version. The move to R-3.3 apparently had quite a few behaviour changes so that new Bioc packages are apparently often incompatible to old ones, so maybe your packages are not all from the new Bioc?

But that it shows that MSnbase imports override mzR imports might be an issue of depends vs imports, maybe? And also a potential real problem in RMassBank, where we have to make sure it uses the correct peaks() definition etc... If it is necessary, we could really just import the essential functions from MSnbase so no mzR functionalty gets overridden.

Also, ggplots2 is apparently an MSnbase dependence. This goes back to the question if we should just copy MSnbase code out instead of depending on it (@sneumann was in favor; I preferred the "one-liner" solution) and work towards having MSnbase keep a separate package for the real basic definitions

**Comment by ermueller** [comment]
> And also a potential real problem in RMassBank, where we have to make sure it uses the correct peaks() definition etc... If it is necessary, we could really just import the essential functions from MSnbase so no mzR functionalty gets overridden.

We have 3 basic solutions, afaik:

1. What you said (Cleanest solution, but has the drawback that later additions using functions from MSnBase would need to be imported)

2. Be exact in code with what package the functions with multiple definitions come from - i.e. using :: appropriately. (Still a pretty clean solution, less of a hassle, but more prone to error in the future if you're not careful)

3. We could just change the import order (Which is basically a "duct tape solution")

I'm not really against 1 or 2? 
3 could maybe be additionally done as a "safety measure".

Also, aren't the overwritten ggplot2 functions just *extensions*? Backwards compatible to pure ggplot2, so to speak?

**Comment by sneumann** [comment]
Hi, maybe @lgatto has some recommendations how to minimize 
the required dependencies ? Yours, Steffen

**Comment by schymane** [comment]
So, for the record, upgrade to the latest R-devel and starting with a clean library (not an old package library) was the only solution to stop BioC (and rJava) bellyaches. All other attempts ended in warnings and errors.
> sessionInfo()
R Under development (unstable) (2016-01-03 r69847)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
locale:
[1] LC_COLLATE=German_Switzerland.1252  LC_CTYPE=German_Switzerland.1252    LC_MONETARY=German_Switzerland.1252
[4] LC_NUMERIC=C                        LC_TIME=German_Switzerland.1252    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] RMassBank_1.99.7     Rcpp_0.12.2          BiocInstaller_1.21.2
loaded via a namespace (and not attached):
 [1] plyr_1.8.3            rcdklibs_1.5.8.4      bitops_1.0-6          ProtGenerics_1.3.3    iterators_1.0.8      
 [6] tools_3.3.0           zlibbioc_1.17.0       MALDIquant_1.14       digest_0.6.8          preprocessCore_1.33.0
[11] gtable_0.1.2          lattice_0.20-33       png_0.1-7             foreach_1.4.3         yaml_2.1.13          
[16] parallel_3.3.0        rJava_0.9-7           stringr_1.0.0         S4Vectors_0.9.15      IRanges_2.5.18       
[21] stats4_3.3.0          grid_3.3.0            Biobase_2.31.3        impute_1.45.0         rcdk_3.3.2           
[26] XML_3.98-1.3          BiocParallel_1.5.12   limma_3.27.7          ggplot2_2.0.0         reshape2_1.4.1       
[31] mzR_2.5.2             magrittr_1.5          scales_0.3.0          pcaMethods_1.61.0     codetools_0.2-14     
[36] BiocGenerics_0.17.2   fingerprint_3.5.2     mzID_1.9.0            MSnbase_1.19.7        colorspace_1.2-6     
[41] stringi_1.0-1         affy_1.49.0           RCurl_1.95-4.7        munsell_0.4.2         doParallel_1.0.10    
[46] rjson_0.2.15          vsn_3.39.0            affyio_1.41.0

**Comment by ermueller** [comment]
I tried it with a clean R 3.2 and it worked. It probably has to do with (like Michele said) some Bioc packages being from devel and others not.

I just found out about this:
 
    biocValid() 

checks whether all bioc packages are from the same release. I think we should make a note of that, in case something like this turns up again...

**Comment by ermueller** [comment]
There definitely are some update quirks with biocLite. This is probably something inside

https://bioconductor.org/biocLite.R

and it occurs when you have an R devel version installed alongside with a release version and already have downloaded bioc packages with the release version. The script doesn't recognize R as a current version and then something goes wrong.

For the record: I uninstalled all R packages except for the base packages, ran this again, and then it worked.

We should probably write to the bioc team about this?

**Comment by uchem-massbank** [comment]
I deinstalled all previous versions of R first and still had problems until we used the clean library, so maybe it’s the old packages that are at fault and not the parallel R versions? But it certainly was a nightmare because on Dec 31 nothing worked, not even biocLite and it was our uchem-massbank R which had been working for us without problems until then... this was the R we had until this morning:
> sessionInfo()
R Under development (unstable) (2014-06-23 r66008)
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by tsufz** [comment]
I guess, this is no issues anymore.
