### ISSUE TITLE
MS$RELATED_MS usage

### ISSUE THREAD

**Issue by tsufz** [MassBank/RMassBank#141]
We may consider to use the MS$RELATED_MS field in future to link internally to related records, i.e. records with other NCE.

**Comment by schymane** [comment]
This field isn't defined in the record specifications, this instead recommends to use the comment fields to link related spectra. It'd be possible to do but a bit complicated to be consistent, I'd say low priority. A good spectral search function would be more useful.

**Comment by tsufz** [comment]
Yeah, but the comment field requires a secondary tag to redirect to the correct dispatcher.

**Comment by meowcat** [comment]
@tsufz @schymane Is this still relevant?

**Comment by schymane** [comment]
I think this can be achieved in other ways with the same structure ... suggest to close. This would require a lot of maintenance to remain current/up-to-date.
