### ISSUE TITLE
RmbSpectrum2: extensibility?

### ISSUE THREAD

**Issue by meowcat** [MassBank/RMassBank#143]
Hi,

I am currently in a situation where I would want additional fields in RmbSpectrum2 (practically, I would want a "noise" field in it. But there could be others that other people could want in different situations).  

What should I do?
- make a custom class for my case which doesn't go into RMassBank
- make an extensible custom class RmbSpectrum2Ext with an additional data.frame where ALL possible additional fields could go into
- change RmbSpectrum2 and add the data.frame in there, making sure there is no upgrade path problem?

Opinions?

**Comment by sneumann** [comment]
Hi, without knowing the details, 1) for the prototype and then 3) for the polished design 
sounds best. We don't expect RMB2 to be set in stone. Happy to chat about it by skype to get the details.

**Comment by ermueller** [comment]
I'd definitely rule out 2 - A functionality like that would be for advanced users anyways. If they go beyond the level of "using RMB classes as intended currently", then it'll probably also be no big deal for them to quickly write up a class that inherits the RmbSpectrum2 class themselves. :)

Probably do 1., but you definitely could do 3. if you feel that it'd be useful to others in the future.

**Comment by meowcat** [comment]
In the current s4power branch I added support for a RmbSpectrum2Ext class, I find it so useful that I propose to merge it into RmbSpectrum2.

**Comment by meowcat** [comment]
@sneumann @schymane @ermueller This is working now, including updates from old workspaces. Do you object to merging it into the main branch?

**Comment by schymane** [comment]
No objections from me.
