### ISSUE TITLE
msmsWorkflow: Step 3. Aggregate all spectra: Error: attempt to set 'colnames' on an object with less than two dimensions

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#144]
Hi, I am currently trying Erik's d2a8695e3940b2512205c9e98bf9e07846784433 
with the CASMI data and "unknown". The data is acquired with MS1+MS2 (data-dependent)
and the two found peak below (1: peaks: 3655, 2: peaks: 4278) are the (noisy) MS2 spectra, 
so I'll need a threshold later.

RIght now I am stuck at "Step 3. Aggregate all spectra: Error: attempt to set 'colnames' on an object with less than two dimensions". Any quick hints ?

Yours,
Steffen

```
> w <- msmsWorkflow(w, mode="pH", steps=2:8,archivename="CASMI2016", retrieval="unknown")
msmsWorkflow: Step 2. First analysis pre recalibration
  |======================================================================| 100%
msmsWorkflow: Step 3. Aggregate all spectra
Error in `colnames<-`(`*tmp*`, value = "mzFound") : 
  attempt to set 'colnames' on an object with less than two dimensions
In addition: Warning messages:
1: In analyzeMsMs(spec, mode = mode, detail = TRUE, run = "preliminary",  :
  The spectra count of the substance 1 (1 spectra) doesn't match the provided spectra list (2 spectra).
2: In analyzeMsMs(spec, mode = mode, detail = TRUE, run = "preliminary",  :
  The spectra count of the substance 2 (1 spectra) doesn't match the provided spectra list (2 spectra).
> traceback()
5: stop("attempt to set 'colnames' on an object with less than two dimensions")
4: `colnames<-`(`*tmp*`, value = "mzFound")
3: `colnames<-`(`*tmp*`, value = "mzFound")
2: aggregateSpectra(w@spectra, addIncomplete = TRUE)
1: msmsWorkflow(w, mode = "pH", steps = 2:8, archivename = "CASMI2016", 
       retrieval = "unknown")
> w
Object of class "msmsWorkspace"
 with files: 
  - BV32_2.mzML 
  - BV32_2.mzML 
 - 1     foundOK: TRUE 
 - 2     foundOK: TRUE 
Peaks found:
 - 1     peaks: 3655 
 - 2     peaks: 4278 
>  w@spectra[[1]]
An object of class "RmbSpectraSet"
Slot "parent":
Object of class "Spectrum1"
 Retention time: 5:18 
 MSn level: 1 
 Total ion count: 40577 
 Polarity: -1 

Slot "children":
RmbSpectrum2List of length 1
names(1): 1224

Slot "found":
[1] TRUE

Slot "complete":
[1] NA

Slot "empty":
[1] NA

Slot "formula":
[1] ""

Slot "id":
[1] "1"

Slot "mz":
[1] 387.94

Slot "name":
[1] "Challenge 1"

Slot "mode":
[1] "pH"
```

**Comment by sneumann** [comment]
I guess the issue is triggered here;
https://github.com/ermueller/RMassBank/blob/master/R/leMsMs.r#L1030

**Comment by ermueller** [comment]
There was a warning in there:

> The spectra count of the substance 1 (1 spectra) doesn't match the provided spectra list (2 spectra).

See, the thing with the CASMI data is that the MS2 spectra have different m/z isolation - even if they follow the same MS1. There are actually 4 MS2 after every MS1, but the first 3 have different isolation m/z's and the 3rd and 4th are the same.

1: 387.94
2: 389.94
3: 391.94
4: 391.94

I could send you the settings, but it seems like the ipb halle mailserver is down? I can't get into the webclient, at least :( Just delete the second spectrum in the spectrumList in the settings - then everything should be fine.
I could send you the settings

**Comment by ermueller** [comment]
Can we close this?

**Comment by schymane** [comment]
Think so, it was an error in the settings?
Or is there a catch that can/should be built in?

**Comment by meowcat** [comment]
If this ever shows up again, we will post a new issue.
