### ISSUE TITLE
Test xcms and mzR workflow on Q-Exactive GC data

### ISSUE THREAD

**Issue by tsufz** [MassBank/RMassBank#146]
I measured a mix of some non-polars with DDA (w and w/o inclusionlist). I will send the spectra to Erik as soon I processed the compounds list. Maybe end of January. The spectra are EI (70 eV) like with HCD fragmentation at levels from NCE 5 (lowest possible) to NCE 50 or so. With NCE 80 they are almost destroyed ;-).

**Comment by meowcat** [comment]
@tsufz What's the status? Still relevant?

**Comment by tsufz** [comment]
No
