### ISSUE TITLE
RmbSettingsTemplate(): systematic shift as default

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#147]
Hi,

as naive user I would not expect a systematic rtShift as default. 
I suggest to set this to 0 in RmbSettingsTemplate(). Any objections ?
````
# Systematic retention time shift
rtShift: -0.3
````
Yours, Steffen

**Comment by schymane** [comment]
I agree to set it to zero, we should have done that ages ago. You seem to be missing a . in the 0.3 though? Strange.
Also reset the licence to CC BY if this has not already been done?
