### ISSUE TITLE
function(files)

### ISSUE THREAD

**Issue by tsufz** [MassBank/RMassBank#148]
The function searches for // to recognise the EOF. If more than one // are in the file (eg. 
PUBLICATION: Beisken S et al (2014) Scientific Data, 1:140029, DOI:10.1038/sdata.2014.29. http://www.ebi.ac.uk/metabolights/MTBLS38) in ML000101 then it failes because it only searches for the first occurrence.

This is important for the splash function, it gets:

.addSplashToRecord("d:/MassBank/dum_160119/DB/Annotation/MetaboLights/ML000101.txt")
   | 
 
       |   0%
Error in parseMassBank(f) : object 'PKPeak' not found In addition: Warning message:
In if (PKStart < endslash) { :
   the condition has length > 1 and only the first element will be useds records for any reason:

**Comment by ermueller** [comment]
Did you get my mail? The fix for this is already in my repo :) It now takes the last occurrence of "//".

**Comment by uchem-massbank** [comment]
That’s the first mail I got from you today…

**Comment by ermueller** [comment]
Really? I wrote 2 mails today, one because getSplash() didn't work, and one because of the "//" stuff

**Comment by schymane** [comment]
Unfortunately yes – only had mails from Tobi and Steffen so far today – didn’t even land in junk or anything.

**Comment by sneumann** [comment]
Same here. Uni Mail playing tricks :-1:

**Comment by ermueller** [comment]
The mails are in my outbox, but the mailserver is doing bloody nothing to actually send them. Well, the first one should have been sent to @sneumann at least but nothing to anybody else. What the heck?

**Comment by ermueller** [comment]
I'll close this, since it is the main repo now.
