### ISSUE TITLE
Drastic slowdown in step 2 

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#150]
Hi, I haven't timed it, but we perceive a drastic performance decrease in Step 2 
with CASMI data from Waters Instruments. Performance was fine this morning, 
then I pulled from RMassBank master and Erik today and we'll die from caffeine poisoning :-)
The changes that came in are below, Erik guessed it could be in formulaCalculator.R 
in Step2. 
Yours, Steffen

````
RMassBank $ git pull origin master
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 17 (delta 5), reused 5 (delta 5), pack-reused 7
Unpacking objects: 100% (17/17), done.
From https://github.com/MassBank/RMassBank
 * branch            master     -> FETCH_HEAD
Updating ea9850e..d05725f
Fast-forward
 R/createMassBank.R    |    2 +-
 R/formulaCalculator.R |   12 ++++++++++
 R/leCsvAccess.R       |   59 +++++++++++++++++++++++++++++++++++--------------
 inst/RMB_options.ini  |    4 ++--
 4 files changed, 57 insertions(+), 20 deletions(-)
````

**Comment by meowcat** [comment]
Hi,

there should not have been any changes in how Step 2 performs because of these changes. Are you sure you used the same settings for both runs?

**Comment by sneumann** [comment]
Right, settings were changed.
