### ISSUE TITLE
Minor bug in compound list import

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#152]
If the first entry of the compound list doesn't contain a retention time in column RT, this gives an error:
w <- msmsRead(w,readMethod = "mzR",mode=RMB_mode, filetable = "fileList.csv")
   0%Error in rt + getOption("RMassBank")$rtShift : 
  non-numeric argument to binary operator

If the entry is changed to zero instead of empty, RT is read correctly as numeric and the error is gone. 
Don't know if this should be included as part of checking the list, or whether it can be fixed as import as numeric...

**Comment by ermueller** [comment]
It was a missing "as.numeric()" in the findRt function. Coercing variables while loading the compound list would do the same thing, but is more complicated. Since the compound list is meant to be accessed by the "findX" functions, this should be ok, right?

**Comment by ermueller** [comment]
Oh yeah, it's in 3998a43f51949e264a4721480e73a8814504c131

**Comment by uchem-massbank** [comment]
Sounds about right to me, thanks ;)
