### ISSUE TITLE
mbWorkflow data structure [request for comments]

### ISSUE THREAD

**Issue by meowcat** [MassBank/RMassBank#153]
I would like to propose a change in the data structure in mbWorkflow.

Currently, in step 4, when the compiled records are generated, all metadata are combined with the spectrum peak list to generate a tree-like MassBank record. 
- input data: a list of `RmbSpectraSet` objects (compounds) containing n `@children (RmbSpectrum2)` each
- output data: a 2-level tree of records (list in a list), where the first level is the compound (corresponding to the `RmbSpectraSet`s and the second level is each spectrum per compound (corresponding to the `children`) That entry is then the MassBank record in "treelist" format.

In step 5, basically all that happens is that the trees are flattened to a text output file.

My proposition is that we keep the output in treelist format exactly the same, but without already processing the peak and annotation table, and put it in RmbSpectrum2 objects. We can directly use the `@info` slot for that. The new output of step 4 would then be
- like the input, a list of `RmbSpectraSet` objects (compounds) containing n `@children (RmbSpectrum2)` each, with the MassBank metadata in `@info`.

In step 5, the same thing will still be done, with the little change that peak and annotation table are flattened only here.

**This has the advantage** that writing a MassBank record happens directly from a RmbSpectrum2 object, and it is straightforward and intuitive to implement output into other formats. The same output function can be applied to spectra before or after mbWorkflow annotation, for example (a coworker, for example, needs unfiltered and unprocessed spectra to compare to the filtered and processed ones.)

I don't think too many things depend on the current structure, except maybe parseMassBank. I would do all the work.

Please comment @sneumann @schymane @ermueller

**Comment by meowcat** [comment]
wrt backwards compatibility, we probably don't have to worry about that at all, because nobody ever stored / loaded ```mbWorkspace``` type objects.

**Comment by sneumann** [comment]
+1 for the proposal, which looks like making things much simpler. 
What is the timing ? BioC release is in early April, i.e. ~8 weeks 
from now. Wouldn't be bad to have this in before ?

**Comment by meowcat** [comment]
As soon as I merge the S4power branch I can start on this, I guess...

**Comment by schymane** [comment]
Sounds like a good idea to me ;)

**Comment by ermueller** [comment]
I really like this idea, too

**Comment by meowcat** [comment]
This is in fact realized
