### ISSUE TITLE
Increase accuracy of retention time?

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#157]
AC$CHROMATOGRAPHY: RETENTION_TIME is currently accurate to 1 decimal place - I'd suggest we increase that to at least two decimal places, one is certainly not enough any more.
Any thoughts?

**Comment by sneumann** [comment]
Can be changed here:
https://github.com/ermueller/RMassBank/blob/master/R/createMassBank.R#L1257

I'll edit and send @ermueller a pull request. 
Yours,
Helau,
Steffen
