### ISSUE TITLE
Minor bug in SPLASH field generation

### ISSUE THREAD

**Issue by tsufz** [MassBank/RMassBank#161]
In record http://massbank.eu/MassBank/jsp/Dispatcher.jsp?type=disp&id=AU223101&site=33, the SPLASH is wrongly parsed with a leading 'SPLASH' before the #

PK$SPLASH: SPLASH splash10-0z00000000-444235979dda46ec1590

The correct format is:
PK$SPLASH: splash10-0z00000000-444235979dda46ec1590

As Nikiforos used a clone from Erik, the problem is maybe related to https://github.com/ermueller/RMassBank/blob/master/R/createMassBank.R line 1467:
 mbdata[["PK$SPLASH"]] <- list(SPLASH = getSplash(peaks[,c("m/z", "int.")]))

The getSplash generates the SPLASH in the correct way.

**Comment by schymane** [comment]
This is also happening in the master branch of this version...not just Erik's version.
MS$DATA_PROCESSING: WHOLE RMassBank 1.99.9
PK$SPLASH: SPLASH splash10-20z0000000-87b7a821054e89de3f7b

**Comment by ermueller** [comment]
Fixed in 4142038a98dc04e3c5161d3e525edd0892e7fe08
