### ISSUE TITLE
Error: “Spectrum2” instead of the required “RmbSpectrum2”

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#166]
http://bioconductor.org/checkResults/devel/bioc-LATEST/RMassBank/malbec1-buildsrc.html
```
Error in initialize(value, ...) : 
  'initialize' method returned an object of class “Spectrum2” instead of the required class “RmbSpectrum2”
Execution halted
```
@meowcat , did MSnBase change anything here ?
Yours, Steffen

**Comment by uchem-massbank** [comment]
This needs a fix ASAP, we still have a build error and release is coming up
https://bioconductor.org/checkResults/3.4/bioc-LATEST/RMassBank/tokay1-buildsrc.html

________________________________________

**Comment by stanstrup** [comment]
Any workaround for this in the meantime?
I was finally getting back to trying this...

**Comment by uchem-massbank** [comment]
This has been discussed intensely on bioc-devel.
Current status is to check the next BioC build to see if Laurent’s fix to MSnbase worked. If so, you’ll need MSnbase 1.99.6.
Older versions of RMassBank (with older versions of MSnbase) should work without problems, we’re still using RMB at the moment... I’m on RMassBank_1.99.10 & MSnbase_1.18.1 – haven’t updated either for a while ;)

**Comment by stanstrup** [comment]
Thanks!
Seems the fix is not on BioC but pulling MSnbase from github worked.

**Comment by sneumann** [comment]
Is fixed now also on BioC on Linux and Windows, after some fix by the MSnbase team.
