### ISSUE TITLE
Vendor-exported centroided data causes R to crash at msmsRead

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#168]
Vittorio reported problems with vendor-exported mzML files (Bruker, unless I am mistaken) and mzR/Rcpp, which caused R to crash as soon as he started msmsRead. This happened after a software upgrade; previous vendor exports worked fine. pwiz-exported mzMLs did not experience this problem.
Not sure if we require any actions on our side, rather just flagging the issue so we can track it.

**Comment by meowcat** [comment]
@schymane Followup or close?

**Comment by schymane** [comment]
The latter ...
