### ISSUE TITLE
Vignette broken "No MS1 data found in Glucolesquerellin_2184_1.mzData"

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#174]
Hi, the xcms vignette is broken with message:

http://bioconductor.org/checkResults/devel/bioc-LATEST/RMassBank/malbec2-buildsrc.html
```
Error in readRawData(fileName(object), includeMSn = includeMSn) : 
  No MS1 data found in file /home/biocbuild/bbs-3.5-bioc/R/library/RMassBankData/spectra.Glucolesquerellin/Glucolesquerellin_2184_1.mzData!
Execution halted
```
@jotsetung and @sneumann are looking into this.

**Comment by jotsetung** [comment]
Seems the file does not contain any MS1 data and that crashes the new code in `xcms`. Will fix.

**Comment by sneumann** [comment]
Hi,  Yes,  this is an MS2 scans only file.

---
I blame Android for the brevity and typos

**Comment by sneumann** [comment]
Fixed in https://github.com/sneumann/xcms/commit/6dec3689c906b8557ebfe3bee91c1592e22852a2

**Comment by sneumann** [comment]
Still leaving a new problem running `R CMD Sweave RMassBankXCMS.Rnw` :
```
Detecting mass traces at 25 ppm ... OK
Detecting features in 32 regions of interest ... OK: 29 found.
Error:  chunk 9 
Error in base::order(mz, method = "radix") : argument lengths differ
Execution halted
```

**Comment by sneumann** [comment]
Turns out that `R version 3.2.3 (2015-12-10)` is too old:
```
> order(c(1,2,3), method="radix")
Error in order(c(1, 2, 3), method = "radix") : argument lengths differ
```
and should not happen on R-devel.

**Comment by schymane** [comment]
Does this mean the problem is solved – or still in progress?
We seem to still have errors (Build Report 31/12)
http://bioconductor.org/checkResults/devel/bioc-LATEST/RMassBank/malbec2-buildsrc.html

**Comment by sneumann** [comment]
There is a fix in xcms on github,
And I failed to use the git-svn and commit to Bioconductor. We are working on it. Yours Steffen

---
I blame Android for the brevity and typos

**Comment by meowcat** [comment]
Seems to be fixed
