### ISSUE TITLE
Write CH$LINK in alphabetical order

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#188]
Hi, the [MassBank specification](https://github.com/MassBank/MassBank-web/blob/master/Documentation/MassBankRecordFormat.md#table-1--massbank-record-format-summary-not-updated)
requires alphabetical order for e.g. `CH$LINK`s:
`Note 1. Within each tag, data fields should be arranged by the alphabetical order of subtag names.`
Rene's validator is now checking for that, and Michael's [pull request](https://github.com/meier-rene/MassBank-data/pull/4) shows that RMB is writing them in a different order.
Is it enough to change the list creation in https://github.com/MassBank/RMassBank/blob/master/R/createMassBank.R#L103 ? And/or simply sort [`link`](https://github.com/MassBank/RMassBank/blob/master/R/createMassBank.R#L716) in `gatherData()` before adding to `mbdata` (also in [`gatherDataBabel()`](https://github.com/MassBank/RMassBank/blob/master/R/createMassBank.R#L856)) and `gatherDataUnknown()` further down ? Or only cope at the end in [`toMassBank()`](https://github.com/MassBank/RMassBank/blob/master/R/createMassBank.R#L1822)

**Comment by meowcat** [comment]
Hi,
disregard the current Master branch as far as MassBank record creation goes; this is basically handled entirely differently now. Most of it but not all is in the S4power branch. I will tend to this but not immediately...

**Comment by schymane** [comment]
I am closing this for now because it was agreed to remove this requirement from the specifications ...
