### ISSUE TITLE
ChemSpider API direct documentation links / future migration

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#192]
ChemSpider have taken down documentation of their current API, the old pages can be found here:
MassSpecAPI – http://www.chemspider.com/MassSpecAPI.asmx
Search - http://www.chemspider.com/Search.asmx
InChI - http://www.chemspider.com/InChI.asmx
Spectra - http://www.chemspider.com/Spectra.asmx

New APIs are being developed but they appear to still be maintaining the old ones for now according to their website. I'm flagging this now so we have the old documentation on record and can keep an eye on potential deprecation time frame ... 
http://www.chemspider.com/AboutServices.aspx?

**Comment by schymane** [comment]
Is anyone interested in working with ChemSpider to investigate the new API? @sneumann anyone from your side? Potential implications for MetFrag even greater @c-ruttkies

**Comment by meowcat** [comment]
Hi @schymane,
thanks for catching that. I just checked, seems like the one command used in RMB is "InChIKeyToCSID". My suggestion is to wait for a while. Maybe there will be some R package springing up that deals with it for us.

The new API requires a personal API key - I don't know if for all requests, but at least for the InChI key to CSID conversion  - so I'm not sure we could "include" one with RMassBank since it would be "open", and I don't really want to have the user set up an InChIKey in the settings...

https://developer.rsc.org/compounds-v1/apis/post/filter/inchikey

**Comment by tsufz** [comment]
Hi, We should start discussion with RCS. Obviously, they want to protect their API services in order of a better marketing for commercial usages. However, there should be a way to get this information without a key. This will stop any contributions by companies as they will not pay just to get data for the processing of MassBank records...

**Comment by schymane** [comment]
Are you volunteering to take a lead role in discussions @tsufz? They have approached us to talk, I would add you into the conversation.

**Comment by tsufz** [comment]
> on potential deprecation time frame
I got an email today, legacy API will be deprecated end of 2018.

**Comment by tsufz** [comment]
> Are you volunteering to take a lead role in discussions @tsufz? They have approached us to talk, I would add you into the conversation.
Yes, but not before end of May or so.

**Comment by schymane** [comment]
Done. @sneumann you've been volunteered too :-) blame me *ducks*

**Comment by tsufz** [comment]
Will be end of November 2018:
http://link.rsc.org/rsps/m/xSq8Cm8ovjN8-Elm0eYB3Sey61zutqNIUUaMcyc14sQ

**Comment by schymane** [comment]
See: https://github.com/ropensci/webchem/issues/149#issuecomment-430987606 
@meowcat  was right :-)
https://github.com/NIVANorge/chemspideR

**Comment by tsufz** [comment]
Hmm, time to skip? You need to supply your token to reveive data from the new API... so far I understood correctly. With this policy they will get unlinked in future...

**Comment by tsufz** [comment]
One can send 1000 per month per free, but needs efforts on all sides (except for CS, they already implemented), the user needs an account and we need to refactorise our code :-(

**Comment by tsufz** [comment]
should process remaining records soon...

**Comment by schymane** [comment]
I suggest the way forward here is to modify our getCSID function to return NA (or similar) and a warning message once the old API is shut down; we can still use e.g. CTS as a source of CSIDs in RMB as we had this from the beginning. getCSID was a relatively late addition. Agreed @meowcat ?
I use getCSID in my packages so we still need the function present to avoid downstream breakages.

The better option for adding CSIDs in MassBank records down the track would likely be to do this via https://github.com/MassBank/MassBank-data (upon record submission) and validation where we can use https://github.com/NIVANorge/chemspideR and our own tokens without making this public or being a part of the BioC daily build/checks ... 
@meier-rene do you think this would be a routine we could build into the validation (check if CSIDs are present, if not, add them in?)

**Comment by meier-rene** [comment]
Yes, we preparing a tool which should augments existing records with additional information(atm. for INCHIKEY and PUBCHEM ID ). This could be applied routinely to update to new accessions/IDS and so on and im pretty sure could be extended to other sources as well.

**Comment by schymane** [comment]
I have just checked our code and we should be covered:
https://github.com/MassBank/RMassBank/blob/master/R/createMassBank.R#L523
and 
https://github.com/MassBank/RMassBank/blob/master/R/webAccess.R#L376 

The latter already checks if ChemSpider is offline and returns a warning and NA, the former tries cactus second if the first function fails. I guess we will see for sure end of November and can close this issue then if no new error messages crop up.
