### ISSUE TITLE
Create project tags

### ISSUE THREAD

**Issue by tsufz** [MassBank/RMassBank#194]
See https://github.com/MassBank/MassBank-web/issues/88 for details

**Comment by tsufz** [comment]
closed with 812c4c7d10ca94425947724ad6f813f875eac5eb

**Comment by tsufz** [comment]
Sorry, wrong repository. Project tags are specified with 812c4c7d10ca94425947724ad6f813f875eac5eb.

**Comment by pstahlhofen** [comment]
Fixed in https://github.com/MassBank/RMassBank/commit/323ec1025f2807270541d46ada9f5b68b6e2a067
