### ISSUE TITLE
Update documentation for BiocManager changes

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#196]
Dear bioc-devs,
A month ago we notified you about our "next generation" changes to BiocInstaller.
Thanks to all beta testers and those who provided feedback and suggestions for a new package name.
I am pleased to inform you that BiocManager is now on CRAN:
https://cran.r-project.org/web/packages/BiocManager/index.html
As mentioned in our last email, you can now install BiocManager using:
```
install.packages("BiocManager")
BiocManager::install("YourPackageNameHere")
```

Action Item:
   -   Please modify the vignettes in your bioc-devel packages to reflect the use of BiocManager

After the next couple of weeks or so, we will be identifying packages in bioc-devel (3.8) that still mention BiocInstaller / biocLite.

**Comment by sneumann** [comment]
Hm, where are we mentioning `biocLite`/`BiocInstaller` ? I could not find anything with `find RMassBank -type f | xargs grep -i biocLite` and the section "Installation and loading" in `RMassBank.Rnw` only mentions "available from Bioconductor". Lets wait if another message comes through, or if this is a false positive by BioC people. Yours, Steffen

**Comment by meowcat** [comment]
No, I don't think we highlight that anywhere specifically.
