### ISSUE TITLE
getCtsKey: Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#198]
On all architectures we have a CHECK error in the CTS checks:
```
> k <- getCtsKey("benzene", "Chemical Name", "InChIKey")
Error: $ operator is invalid for atomic vectors
Execution halted
```
http://bioconductor.org/checkResults/devel/bioc-LATEST/RMassBank/malbec1-checksrc.html

**Comment by schymane** [comment]
Is CTS actually working? When I land on the webpage a see an error and can't go further (from phone). That's the usual cause of sudden errors...

**Comment by meowcat** [comment]
It works like half, when I use it manually...

**Comment by tsufz** [comment]
http://cts.fiehnlab.ucdavis.edu/ works

**Comment by schymane** [comment]
When I visit the website I see a “Error 500 When calling /rest/toValues” message which indicates to me that something is wrong somewhere.
Real issue: the error message does not really indicate the problem. By now I know that if we have an atomic vector error, it means CTS is down. Maybe we need to catch this in a slightly more elegant manner and print an error message that is appropriate – or build in a catch so that we no longer fail BioC check when CTS is down …  i.e. if CTS is down we default to another service even in CHECK

**Comment by meowcat** [comment]
I'm not sure CTS being down is actually the issue, since the vignettes seem to build? The error is actually in the examples, not the vignette. Also CTS works every second time I try it. I'll look into it.

**Comment by meowcat** [comment]
The error is indeed with CTS being flaky.

```R

> getCtsKey("benzene")
Error: $ operator is invalid for atomic vectors
> getCtsKey("benzene")
[1] "UHOVQNZJYSORNB-UHFFFAOYSA-N"
> getCtsKey("benzene")
[1] "UHOVQNZJYSORNB-UHFFFAOYSA-N"
> getCtsKey("benzene")
Error: $ operator is invalid for atomic vectors
> getCtsKey("benzene")
Error: $ operator is invalid for atomic vectors
> getCtsKey("benzene")
[1] "UHOVQNZJYSORNB-UHFFFAOYSA-N"
> getCtsKey("benzene")
Error: $ operator is invalid for atomic vectors
> getCtsKey("benzene")
[1] "UHOVQNZJYSORNB-UHFFFAOYSA-N"
```

**Comment by schymane** [comment]
Yes this is what I suspected. I suggest (a) we try to catch the error and change it to a warning and (b) redirect it to generating an InChIKey another way if CTS fails. We have enough fallbacks now. You could try to just make it re-query CTS but it’s clear it’s a CTS performance issue again and this will not always work [I have reported it to CTS btw through bitbucket]

**Comment by meowcat** [comment]
As a sidenote, we might want to migrate to webchem or such instead of keeping our own CTS querying tools up to date (or not so up to date)... https://github.com/ropensci/webchem

**Comment by schymane** [comment]
This CTS issue we’ve had from the beginning iirc. We never caught this nicely.
We can consider migration but it’s likely more work, I’m not volunteering at this stage but we already flagged it … https://github.com/MassBank/RMassBank/issues/195

**Comment by meowcat** [comment]
Just to throw it out there, as far as the tests/examples go it would also be an idea to cache the responses with https://github.com/ropensci/vcr / https://github.com/ropensci/webmockr, so that the tests only check the behaviour of the R function and not of the webservice. I think we'd have to move to crul instead of curl for that. Not something I do today or tomorrow but in the future possibly yes.

**Comment by meowcat** [comment]
Hi,

Apparently I waited the error out and now it builds successfully. Was there any feedback from CTS?

**Comment by schymane** [comment]
I didn’t get any direct reply from them :-(

**Comment by sneumann** [comment]
Hi, on macOS we have again this issue, and a check ERROR.
I found that I get that error in the console, but it vanishes 
when loading RCurl. 
````
> library(RMassBank)
> k <- getCtsKey("benzene", "Chemical Name", "InChIKey")
 Error: $ operator is invalid for atomic vectors 
> library(RCurl)
> library(rjson)
> k <- getCtsKey("benzene", "Chemical Name", "InChIKey")
``````

I also found that while the above indeed happened, 
I can't reproduce 10 Minutes later. Closing again.
Yours, Steffen

**Comment by schymane** [comment]
We probably need a better error handling for this. This uninformative error comes when the function returns "NA", i.e. when the web retrieval fails for any reason. 
This is currently failing permanently in windows and causing build errors ... see #250

**Comment by sneumann** [comment]
We still / again have this in 2.99.2. Yours, Steffen

**Comment by schymane** [comment]
Strange .. it works for me with the install from github yesterday.
Indeed  ... build reports show (different) errors to previous ones now. Not sure what to do about this?

```
> library(devtools)
Loading required package: usethis
> install_github("MassBank/RMassBank",dependencies=F,ref="main")
[cut]
> getCtsKey("benzene")
[1] "UHOVQNZJYSORNB-ZDOIIHCHSA-N" "UHOVQNZJYSORNB-IGMARMGPSA-N"
[3] "UHOVQNZJYSORNB-WDBXEELJSA-N" "UHOVQNZJYSORNB-UHFFFAOYSA-N"
[5] "UHOVQNZJYSORNB-IDEBNGHGSA-N"
```

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMassBank_2.99.2 Rcpp_1.0.2       devtools_2.2.1   usethis_1.5.1   

loaded via a namespace (and not attached):
 [1] Biobase_2.44.0        httr_1.4.1            vsn_3.52.0           
 [4] pkgload_1.0.2         foreach_1.4.7         assertthat_0.2.1     
 [7] BiocManager_1.30.10   affy_1.62.0           stats4_3.6.1         
[10] yaml_2.2.0            rcdklibs_2.0          remotes_2.1.0        
[13] impute_1.58.0         sessioninfo_1.1.1     pillar_1.4.2         
[16] backports_1.1.5       lattice_0.20-38       glue_1.3.1           
[19] limma_3.40.6          fingerprint_3.5.7     digest_0.6.21        
[22] colorspace_1.4-1      preprocessCore_1.46.0 plyr_1.8.4           
[25] MALDIquant_1.19.3     XML_3.98-1.20         pkgconfig_2.0.3      
[28] zlibbioc_1.30.0       purrr_0.3.3           itertools_0.1-3      
[31] scales_1.0.0          processx_3.4.1        affyio_1.54.0        
[34] BiocParallel_1.18.1   tibble_2.1.3          IRanges_2.18.3       
[37] ggplot2_3.2.1         ellipsis_0.3.0        withr_2.1.2          
[40] BiocGenerics_0.30.0   lazyeval_0.2.2        cli_1.1.0            
[43] magrittr_1.5          crayon_1.3.4          memoise_1.1.0        
[46] ps_1.3.0              fs_1.3.1              ncdf4_1.16.1         
[49] doParallel_1.0.15     MASS_7.3-51.4         pkgbuild_1.0.6       
[52] mzR_2.18.1            tools_3.6.1           prettyunits_1.0.2    
[55] MSnbase_2.10.1        S4Vectors_0.22.1      munsell_0.5.0        
[58] rcdk_3.4.7.1          callr_3.3.2           pcaMethods_1.76.0    
[61] compiler_3.6.1        mzID_1.22.0           rlang_0.4.5          
[64] grid_3.6.1            iterators_1.0.12      rstudioapi_0.10      
[67] rjson_0.2.20          testthat_2.2.1        gtable_0.3.0         
[70] codetools_0.2-16      curl_4.2              R6_2.4.1             
[73] dplyr_0.8.5           rprojroot_1.3-2       ProtGenerics_1.16.0  
[76] desc_1.2.0            rJava_0.9-11          parallel_3.6.1       
[79] png_0.1-7             tidyselect_1.0.0     
```

**Comment by sneumann** [comment]
In 00101559ae3ab1c841c8026366216abde278d07b I added a check to catch status codes. 
CTS was failling with `500` errors. Pushed to main, dev and upstream master. Yours, Steffen

**Comment by schymane** [comment]
Great, thanks! Hopefully this will help diagnose, we may need to do a better test here:
https://github.com/MassBank/RMassBank/blob/main/R/webAccess.R#L280

 as this is where the atomic vector error comes from: 
https://github.com/MassBank/RMassBank/blob/main/R/webAccess.R#L285

So it was just bad luck / bad timing that CTS was down only on the win builds?

**Comment by sneumann** [comment]
Indeed. The correct approach is to think 1) what can go wrong and 2) what do we return in that case. Yours, Steffen

**Comment by schymane** [comment]
Is this something @pstahlhofen can look into? It's likely just a minor tweak, I assume we can take care of `NULL` downstream but we just need to catch this atomic vector error better (and return NULL not an error...)

**Comment by sneumann** [comment]
For the cleanup / harmonisation I want to start with the documentation of the wanted behaviour first, 
so if Paul creates an overview of which functions have something like `GET()` in them that'd be a start. 
We'll have to work with 1) Correct results, i.e. some valid response. 2) Nothing found (e.g. InchiKey ABCDEF-GHIJKLM-N)
and 3) remote end broken. Different services might indicate these three states differently, so that needs to be found and documented as well (Returning response or empty string ? return code 200, 404, 500 ?). Once we have that inventory, 
we can do the cleanup stuff. Yours, Steffen

**Comment by tsufz** [comment]
Well, I do an update to BioC 3.12 and test it later.

**Comment by pstahlhofen** [comment]
Sure, I can look into it :)
@sneumann does this have priority before #216 ?
Cause this is what I started to do now. Also, do I correctly assume that this is about 'GET' functions in the API? So what are the main scripts I should look into?

**Comment by sneumann** [comment]
Just for the record, `2.99.3` didn't make it into todays Build report, but today `2.99.2` erred (errored ?) on two different architectures. .

**Comment by schymane** [comment]
...so in today's report now win is good ... and 1*linux and mac not. So it's a random CTS unavailability... why always twice I wonder...

**Comment by tsufz** [comment]
On my Win R 4.0.3 with BioC 3.12 all run through, except the warning in #259.

**Comment by pstahlhofen** [comment]
@sneumann if `2.99.2` is 9033bc4cfdca40df5c47524c8c31e98aa then it indeed fails in macOS (at least on my architecture) due to the getCtsKey error, but on `2.99.3` it works fine, so your changes fixed it for me. Thanks!
For the `2.99.3` version, I don't get the same warnings as @tsufz described in #259
The warnings I get are mainly related to documentation

**Comment by sneumann** [comment]
Very good evening indeed, only warnings left.
However, we need to certainly adress the warnings. Yours, Steffen

**Comment by schymane** [comment]
Hooray!!!
