### ISSUE TITLE
msmsWorkflow fails at Step 2 with most recent rcdks

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#199]
The latest rcdks come with very verbose messages and (currently doing RMassBank on unfamiliar files) I get failure at 
w <- msmsWorkflow(w, steps=c(2), mode=RMB_mode, archivename=archive_name)
which is almost certainly due to rcdk - when I replace with an old version of rcdk I can run without issues. The warnings were terribly ugly, culminating in an uninformative error and now long gone as I had to restart R. 
Has anyone managed to successfully used RMB with rcdk > 3.4.8? I tried 3.4.8, the latest 3.4.9 (install_github), have now "downgraded" to 3.4.3 and it's fine. 
https://github.com/rajarshi/cdkr/blob/master/rcdk/DESCRIPTION 

Relates to 
https://github.com/rajarshi/cdkr/issues/66
and the best sessionInfo is there cos I can't print it out now as still calculating ... big files ...

**Comment by sneumann** [comment]
Hi, I can confirm problem with rcdk-3.4.9. Haven't checked in detail, but running 
`R CMD check RMassBank` I get 
```
...
* checking examples ... ERROR
Running examples in ‘RMassBank-Ex.R’ failed
The error most likely occurred in:
> ### Name: findMass
> ### Title: Calculate exact mass
> ### Aliases: findMass
> ### ** Examples
> ##
> findMass("OC[C@H]1OC(O)[C@H](O)[C@@H](O)[C@@H]1O")
248  [main] DEBUG org.openscience.cdk.DynamicFactory  - getting candidates for interface org.openscience.cdk.interfaces.IBond 3
254  [main] INFO  org.openscience.cdk.config.AtomTypeFactory  - Reading config file from org/openscience/cdk/dict/data/cdk-atom-types.owl
...
496  [main] DEBUG org.openscience.cdk.config.atomtypes.OWLAtomTypeHandler  - character data
496  [main] DEBUG org.openscience.cdk.config.atomtypes.OWLAtomTypeHandler  - character data
496  [main] DEBUG org.openscience.cdk.config.atomtypes.OWLAtomTypeHandler  - character data
[1] "Java-Object{java.lang.NullPointerException}"
Error in get.exact.mass(mol) : 
  Couldn't get exact mass. Maybe you have not performed aromaticity, atom type or isotope configuration?
Calls: findMass -> get.exact.mass
Execution halted
```
and later
```
Errors in running code in vignettes:
when running code in ‘RMassBank.Rnw’
  ...
3861 [main] INFO  org.openscience.cdk.formula.MassToFormulaTool  - Creating matrix for isotopes combination
3861 [main] ERROR org.openscience.cdk.formula.MassToFormulaTool  - Proposed mass is out of the range: 203.74409411212656
3861 [main] INFO  org.openscience.cdk.formula.MassToFormulaTool  - Initiate MassToForumlaTool
3861 [main] INFO  org.openscience.cdk.formula.MassToFormulaTool  - Creating matrix for isotopes combination
3866 [main] INFO  org.openscience.cdk.formula.MassToFormulaTool  - Creating matrix for isotopes combination
3866 [main] ERROR org.openscience.cdk.formula.MassToFormulaTool  - Proposed mass is out of the range: 205.2540123250172

  When sourcing ‘RMassBank.R’:
Error: number of columns of matrices must match (see arg 7)
Execution halted
```
so I guess `get.exact.mass` is the actual culprit. And indeed the example 
from the manpage does not work:
```
       m <- parse.smiles('c1ccccc1')[[1]]
     
       ## Need to configure the molecule
       do.aromaticity(m)
       do.typing(m)
       do.isotopes(m)
     
       get.exact.mass(m)

>        get.exact.mass(m)
[1] "Java-Object{java.lang.NullPointerException}"
Error in get.exact.mass(m) : 
  Couldn't get exact mass. Maybe you have not performed aromaticity, atom type or isotope configuration?
```
Yours,
Steffen

```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                 
 [3] LC_TIME=en_US.UTF-8           LC_COLLATE=en_US.UTF-8       
 [5] LC_MONETARY=en_US.UTF-8       LC_MESSAGES=en_US.UTF-8      
 [7] LC_PAPER=en_US.UTF-8          LC_NAME=en_US.UTF-8          
 [9] LC_ADDRESS=en_US.UTF-8        LC_TELEPHONE=en_US.UTF-8     
[11] LC_MEASUREMENT=en_US.UTF-8    LC_IDENTIFICATION=en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rcdk_3.4.9   rcdklibs_2.2 rJava_0.9-10

loaded via a namespace (and not attached):
[1] compiler_3.4.4    tools_3.4.4       parallel_3.4.4    fingerprint_3.5.7
[5] iterators_1.0.10  itertools_0.1-3   png_0.1-7   
```

**Comment by schymane** [comment]
I'm setting this to high priority as it still seems an issue with latest rcdk and I again had to retrofix to 3.4.3 to get RMB to work properly. I have not yet had time to look into it in greater detail.

**Comment by schymane** [comment]
Pasting input from @sneumann 

I have one Linux R here that works:
R (devil version :-)
rcdklibs_2.0
rcdk_3.4.7.1 (newest on CRAN)

and one that does not:
R (version 3.4.4)
rcdklibs_2.2
rcdk_3.4.9

BioC machines have 

malbec1:                                            Version Built
rcdk                                                3.4.7.1 3.5.1
rcdklibs                                                2.0 3.5.1

tokay1:
rcdk                                                3.4.7.1 3.5.1
rcdklibs                                                2.0 3.5.0

=> BioC should have the working version from CRAN,
   so build should work until Rajarshi updates the CRAN version.

**Comment by rajarshi** [comment]
The excessively verbose output issue is now resolved.

The `get.exact.mass` problem remains and I don't have a good fix for that (it seems like an issue on the CDK side)

**Comment by schymane** [comment]
I can confirm that the verbose output seems to have improved recently.
Do you happen to know if get.exact.mass has been replaced by a new function in CDK, or has it just changed behaviour somehow?
We'll have to debug and add a backwards compatible fix ASAP.

**Comment by schymane** [comment]
Documenting email conversation outside github for the record:
Zach:
- the `get.exact.mass` function is a breaking change in the CDK library.  Therefore an update of rCDKlibs (independent of rcdk) to version 2.2 will break that function

Actions suggested by Zach:
1. fixing the `get.exact.mass` issue  - ideally to be backward compatible [rcdk/RMassBank].
2. updating master with a few other small fixes (java 11 compatibility; some doc breakages I ran into when building for CRAN)
3. email other downstream maintainers to check there are not other hidden breakages
4. submit rcdklibs and rcdk at the same time

From @sneumann 
I am not sure it is (only) the get.exact.mass. I am getting 
> library(rcdk)
> mol <- parse.smiles("CCO")[[1]]
> do.aromaticity(mol)
[1] FALSE
> convert.implicit.to.explicit(mol)
Error in get.atoms(molecule) : object 'molecule' not found

which works on 3.4.7.1, but not on 3.4.9 (master)
I think that the issue was introduced in
https://github.com/rajarshi/cdkr/commit/0cb1744bd5a9b202d36fdc8d1b3ed194f61cfe55#diff-7fa6b9bfa770a61d9ade31307ffc61a6L175
where the check (see also below) should call get.atoms(mol)
> convert.implicit.to.explicit
function (mol) 
{
    if (!.check.class(mol,
"org/openscience/cdk/interfaces/IAtomContainer")) 
        stop("molecule must be of class IAtomContainer")
    if (any(is.null(unlist(lapply(get.atoms(molecule), .jcall,

**Comment by schymane** [comment]
Update from Zach (rcdk side) following latest commit with todos that hit the RMassBank team - I have calculations to run today before I can start so if anyone else has a moment ... we need to check that the masses we get out are correct ... and still need to find the get.exact.mass issue

2.	An issue in the '.cdkFormula.createObject' function related to isotope weight calculation that was causing some code to fail with a NullPointer exception.  This code is in  https://github.com/rajarshi/cdkr/pull/80/commits/3d6573f55a1fc8b86f3de4e6c4088e7c881f9f1f 
=> Emma, Steffen, can you check to see that the isotope calculations obtained with this code is correct?
3.	 Issue 3: `get.exact.mass` is still broken. Because it is a nullpointer exception and we already had some issues with the isotope code I am guessing the problem is hidden in the `do.isotope` call.  [Note a test for get.exact.mass should be added to the unittests. ]

**Comment by sneumann** [comment]
Step 2 still not working. Upgraded to github rcdk `3.4.9.1` version.
```
> w <- msmsWorkflow(w, mode="pH", steps=c(2:2), archivename = 
+ 				"pH_narcotics")
msmsWorkflow: Step 2. First analysis pre recalibration
  |                                                                |   0%org.openscience.cdk.formula.MassToFormulaTool ERROR: Proposed mass is out of the range: 199.08532641193125
org.openscience.cdk.formula.MassToFormulaTool ERROR: Proposed mass is out of the range: 201.50309679767344
org.openscience.cdk.formula.MassToFormulaTool ERROR: Proposed mass is out of the range: 201.6891014363453
org.openscience.cdk.formula.MassToFormulaTool ERROR: Proposed mass is out of the range: 201.77395556232187
org.openscience.cdk.formula.MassToFormulaTool ERROR: Proposed mass is out of the range: 203.74409411212656
org.openscience.cdk.formula.MassToFormulaTool ERROR: Proposed mass is out of the range: 205.2540123250172
Error in rbind(...) : 
  number of columns of matrices must match (see arg 7)
```
The `childPeaks <- as.data.frame(do.call(rbind, peakmatrix))` is only where the issue manifests, the problem must be earlier. Digging into the error, the peakmatrix seems to look like:
```
(`1` = list(), `2` = list(), `3` = list(), `4` = list(), `5` = list(), `6` = list(),
 `7` = c("7", "29053.216796875", "70.0644836425781", "C4H8N", "70.0651256761"),
 `8` = list(), `9` = list(), `10` = list(), `11` = list(), `12` = list(),
 `13` = list(), `14` = list(), `15` = list(), `16` = list(), `17` = list(),
 `18` = c("18", "12117.5107421875", "110.99934387207", "C6H4Cl", "110.9996042281"), `19` = c("19", "19145.0703125", "117.057037353516", "C8H7N", "117.0573006441"),
 `20` = c("20", "66625.6640625", "118.065277099609", "C8H8N", "118.0651256761"),
 `21` = c("21", "706805.5", "119.072761535645", "C8H9N", "119.0729507081"),
 `22` = list(),
 `23` = c("23", "15130.951171875", "138.011169433594", "C7H5ClN", "138.0105032601" ),
 `24` = c("24", "262570.03125", "140.026092529297", "C7H7ClN", "140.0261533241"),
 `25` = c("25", "50312.33984375", "145.08854675293", "C10H11N", "145.0886007721"),
 `26` = c("26", "248362.203125", "152.026321411133", "C8H7ClN", "152.0261533241"),
 `35` = c("35", "7671105", "154.041915893555", "C8H9ClN", "154.0418033881"),
 `46` = c("46", "28057.9765625", "160.099670410156", "C10H12N2", "160.0994998041"),
 `47` = c("47", "12471.2021484375", "162.113861083984", "C10H14N2", "162.1151498681"),
 `48` = c("48", "221552.625", "166.042022705078", "C9H9ClN", "166.0418033881"),
 `49` = c("49", "67923.6875", "167.037109375", "C8H8ClN2", "167.0370523561" ),
 `50` = c("50", "20624.45703125", "168.046691894531", "C8H9ClN2", "168.0448773881"),
 `51` = list(),
 `52` = c("52", "34203.89453125", "178.041366577148", "C10H9ClN", "178.0418033881"),
 `53` = c("53", "322292.71875", "180.057754516602", "C10H11ClN", "180.0574534521" ),
 `54` = c("54", "13046.4541015625", "195.070709228516", "C10H12ClN2", "195.0683524841"),
 `56` = c("56", "438676.4375", "197.084564208984", "C10H14ClN2", "197.0840025481"),
 `57` = list(), `58` = list(), `59` = list(), `60` = list(),
 `61` = list(), `62` = list())
```
I don't know the narcotics dataset enough to guess 1) what the cpds with the failling mass are, 
2) what the entries with the empty lists should've been and I don't know RMB code well enough 
to know where the list entries are created, so I could mimick why the empty ones fail on recent rCDK.
Ideas ? Yours, Steffen

**Comment by schymane** [comment]
It's not the same errors I was getting today (the last one overlaps a little) but basically it seems to indicate to me that the latest rcdks still don't quite reproduce the functionality that we rely on fully and I'm not sure it's a problem our side yet as I saw no issues with the masses today with the latest rcdk. It doesn't make sense that our masses are suddenly out of range?
You can find the compound list and infolist with the masses in the repo though, maybe that will help?
I also failed with latest version today, but got normal functionality with 3.4.3.
@meowcat we may need your help here too at some point! It doesn't make sense yet.

-------------------------------------------
PI: EnvCheminf @ LCSB
FNR ATTRACT Fellow
emma.schymanski@uni.lu




On Sat, Nov 10, 2018 at 8:48 PM +0100, "sneumann" <notifications@github.com<mailto:notifications@github.com>> wrote:


Step 2 still not working. Upgraded to github rcdk 3.4.9.1 version.

> w <- msmsWorkflow(w, mode="pH", steps=c(2:2), archivename =
+                               "pH_narcotics")
msmsWorkflow: Step 2. First analysis pre recalibration
  |                                                                |   0%org.openscience.cdk.formula.MassToFormulaTool ERROR: Proposed mass is out of the range: 199.08532641193125
org.openscience.cdk.formula.MassToFormulaTool ERROR: Proposed mass is out of the range: 201.50309679767344
org.openscience.cdk.formula.MassToFormulaTool ERROR: Proposed mass is out of the range: 201.6891014363453
org.openscience.cdk.formula.MassToFormulaTool ERROR: Proposed mass is out of the range: 201.77395556232187
org.openscience.cdk.formula.MassToFormulaTool ERROR: Proposed mass is out of the range: 203.74409411212656
org.openscience.cdk.formula.MassToFormulaTool ERROR: Proposed mass is out of the range: 205.2540123250172
Error in rbind(...) :
  number of columns of matrices must match (see arg 7)


The childPeaks <- as.data.frame(do.call(rbind, peakmatrix)) is only where the issue manifests, the problem must be earlier. Digging into the error, the peakmatrix seems to look like:

(`1` = list(), `2` = list(), `3` = list(), `4` = list(), `5` = list(), `6` = list(),
 `7` = c("7", "29053.216796875", "70.0644836425781", "C4H8N", "70.0651256761"),
 `8` = list(), `9` = list(), `10` = list(), `11` = list(), `12` = list(),
 `13` = list(), `14` = list(), `15` = list(), `16` = list(), `17` = list(),
 `18` = c("18", "12117.5107421875", "110.99934387207", "C6H4Cl", "110.9996042281"), `19` = c("19", "19145.0703125", "117.057037353516", "C8H7N", "117.0573006441"),
 `20` = c("20", "66625.6640625", "118.065277099609", "C8H8N", "118.0651256761"),
 `21` = c("21", "706805.5", "119.072761535645", "C8H9N", "119.0729507081"),
 `22` = list(),
 `23` = c("23", "15130.951171875", "138.011169433594", "C7H5ClN", "138.0105032601" ),
 `24` = c("24", "262570.03125", "140.026092529297", "C7H7ClN", "140.0261533241"),
 `25` = c("25", "50312.33984375", "145.08854675293", "C10H11N", "145.0886007721"),
 `26` = c("26", "248362.203125", "152.026321411133", "C8H7ClN", "152.0261533241"),
 `35` = c("35", "7671105", "154.041915893555", "C8H9ClN", "154.0418033881"),
 `46` = c("46", "28057.9765625", "160.099670410156", "C10H12N2", "160.0994998041"),
 `47` = c("47", "12471.2021484375", "162.113861083984", "C10H14N2", "162.1151498681"),
 `48` = c("48", "221552.625", "166.042022705078", "C9H9ClN", "166.0418033881"),
 `49` = c("49", "67923.6875", "167.037109375", "C8H8ClN2", "167.0370523561" ),
 `50` = c("50", "20624.45703125", "168.046691894531", "C8H9ClN2", "168.0448773881"),
 `51` = list(),
 `52` = c("52", "34203.89453125", "178.041366577148", "C10H9ClN", "178.0418033881"),
 `53` = c("53", "322292.71875", "180.057754516602", "C10H11ClN", "180.0574534521" ),
 `54` = c("54", "13046.4541015625", "195.070709228516", "C10H12ClN2", "195.0683524841"),
 `56` = c("56", "438676.4375", "197.084564208984", "C10H14ClN2", "197.0840025481"),
 `57` = list(), `58` = list(), `59` = list(), `60` = list(),
 `61` = list(), `62` = list())


I don't know the narcotics dataset enough to guess 1) what the cpds with the failling mass are,
2) what the entries with the empty lists should've been and I don't know RMB code well enough
to know where the list entries are created, so I could mimick why the empty ones fail on recent rCDK.
Ideas ? Yours, Steffen

**Comment by schymane** [comment]
I don't get quite the same error or traceback at @sneumann - I just installed the latest rcdk and get the following at step 2:
```

> library("RMassBankData")
> setwd("C:/DATA/R/RMassBank_Demo")
> RmbDefaultSettings()
> w <- newMsmsWorkspace()
> files <- list.files(system.file("spectra", package="RMassBankData"), ".mzML", full.names = TRUE)
> loadList("./Compoundlist.csv") #the default compound list
Loaded compoundlist successfully
> w <- msmsWorkflow(w, mode="pH", steps=c(1:4), archivename = "pH_narcotics")
[Step 1 successful]
msmsWorkflow: Step 2. First analysis pre recalibration
|   0%Error in .Method(..., deparse.level = deparse.level) : 
  number of columns of matrices must match (see arg 6)
```
and with traceback()
```

> traceback()
24: .Method(..., deparse.level = deparse.level)
23: eval(expr, envir, enclos)
22: eval(.dotsCall, env)
21: eval(.dotsCall, env)
20: standardGeneric("rbind")
19: (function (..., deparse.level = 1) 
    standardGeneric("rbind"))(`1` = list(), `2` = list(), `4` = list(), 
        `5` = list(), `6` = list(), `7` = c("7", "29053.216796875", 
        "70.0644836425781", "C4H8N", "70.0651256761"), `8` = list(), 
        `9` = list(), `10` = list(), `11` = list(), `12` = list(), 
        `13` = list(), `14` = list(), `15` = list(), `16` = list(), 
        `17` = list(), `18` = c("18", "12117.5107421875", "110.99934387207", 
        "C6H4Cl", "110.9996042281"), `19` = c("19", "19145.0703125", 
        "117.057037353516", "C8H7N", "117.0573006441"), `20` = c("20", 
        "66625.6640625", "118.065277099609", "C8H8N", "118.0651256761"
        ), `21` = c("21", "706805.5", "119.072761535645", "C8H9N", 
        "119.0729507081"), `22` = list(), `23` = c("23", "15130.951171875", 
        "138.011169433594", "C7H5ClN", "138.0105032601"), `24` = c("24", 
        "262570.03125", "140.026092529297", "C7H7ClN", "140.0261533241"
        ), `25` = c("25", "50312.33984375", "145.08854675293", "C10H11N", 
        "145.0886007721"), `26` = c("26", "248362.203125", "152.026321411133", 
        "C8H7ClN", "152.0261533241"), `35` = c("35", "7671105", "154.041915893555", 
        "C8H9ClN", "154.0418033881"), `46` = c("46", "28057.9765625", 
        "160.099670410156", "C10H12N2", "160.0994998041"), `47` = c("47", 
        "12471.2021484375", "162.113861083984", "C10H14N2", "162.1151498681"
        ), `48` = c("48", "221552.625", "166.042022705078", "C9H9ClN", 
        "166.0418033881"), `49` = c("49", "67923.6875", "167.037109375", 
        "C8H8ClN2", "167.0370523561"), `50` = c("50", "20624.45703125", 
        "168.046691894531", "C8H9ClN2", "168.0448773881"), `51` = list(), 
        `52` = c("52", "34203.89453125", "178.041366577148", "C10H9ClN", 
        "178.0418033881"), `53` = c("53", "322292.71875", "180.057754516602", 
        "C10H11ClN", "180.0574534521"), `54` = c("54", "13046.4541015625", 
        "195.070709228516", "C10H12ClN2", "195.0683524841"), `56` = c("56", 
        "438676.4375", "197.084564208984", "C10H14ClN2", "197.0840025481"
        ), `57` = list(), `58` = list(), `59` = list(), `60` = list(), 
        `61` = list(), `62` = list())
18: do.call(rbind, peakmatrix)
17: do.call(rbind, peakmatrix)
16: as.data.frame(do.call(rbind, peakmatrix))
15: FUN(X[[i]], ...)
14: lapply(as.list(X), FUN = FUN, ...)
13: lapply(as.list(X), FUN = FUN, ...)
12: lapply(msmsPeaks@children, analyzeTandemShot)
11: lapply(msmsPeaks@children, analyzeTandemShot)
10: analyzeMsMs.formula(msmsPeaks, mode, detail, run, filterSettings)
9: analyzeMsMs(spec, mode = mode, detail = TRUE, run = "preliminary", 
       filterSettings = settings$filterSettings, spectraList = settings$spectraList, 
       method = analyzeMethod)
8: FUN(X[[i]], ...)
7: lapply(as.list(X), FUN = FUN, ...)
6: lapply(as.list(X), FUN = FUN, ...)
5: lapply(w@spectra, function(spec) {
       s <- analyzeMsMs(spec, mode = mode, detail = TRUE, run = "preliminary", 
           filterSettings = settings$filterSettings, spectraList = settings$spectraList, 
           method = analyzeMethod)
       nProg <<- nProg + 1
       pb <- do.call(progressbar, list(object = pb, value = nProg))
       return(s)
   })
4: lapply(w@spectra, function(spec) {
       s <- analyzeMsMs(spec, mode = mode, detail = TRUE, run = "preliminary", 
           filterSettings = settings$filterSettings, spectraList = settings$spectraList, 
           method = analyzeMethod)
       nProg <<- nProg + 1
       pb <- do.call(progressbar, list(object = pb, value = nProg))
       return(s)
   })
3: .class1(object)
2: as(lapply(w@spectra, function(spec) {
       s <- analyzeMsMs(spec, mode = mode, detail = TRUE, run = "preliminary", 
           filterSettings = settings$filterSettings, spectraList = settings$spectraList, 
           method = analyzeMethod)
       nProg <<- nProg + 1
       pb <- do.call(progressbar, list(object = pb, value = nProg))
       return(s)
   }), "SimpleList")
1: msmsWorkflow(w, mode = "pH", steps = c(1:4), archivename = "pH_narcotics")
```

and sessionInfo()
```

> sessionInfo()
R version 3.2.5 (2016-04-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMassBankData_1.8.0 RMassBank_2.3.1     Rcpp_0.12.17       

loaded via a namespace (and not attached):
 [1] pillar_1.1.0          BiocInstaller_1.20.3  futile.logger_1.4.3   plyr_1.8.4           
 [5] rcdklibs_2.2          bitops_1.0-6          iterators_1.0.8       futile.options_1.0.0 
 [9] ProtGenerics_1.2.1    tools_3.2.5           zlibbioc_1.16.0       digest_0.6.12        
[13] MALDIquant_1.15       tibble_1.4.1          preprocessCore_1.32.0 gtable_0.2.0         
[17] lattice_0.20-33       png_0.1-7             rlang_0.1.6           foreach_1.4.3        
[21] yaml_2.1.14           parallel_3.2.5        rJava_0.9-8           stringr_1.2.0        
[25] S4Vectors_0.8.11      IRanges_2.4.8         stats4_3.2.5          grid_3.2.5           
[29] Biobase_2.30.0        impute_1.44.0         rcdk_3.4.9.1          XML_3.98-1.5         
[33] BiocParallel_1.4.3    limma_3.26.9          ggplot2_2.2.1         reshape2_1.4.2       
[37] mzR_2.4.1             lambda.r_1.1.9        magrittr_1.5          itertools_0.1-3      
[41] scales_0.5.0          pcaMethods_1.60.0     codetools_0.2-14      BiocGenerics_0.16.1  
[45] fingerprint_3.5.4     mzID_1.8.0            MSnbase_1.18.1        colorspace_1.3-2     
[49] stringi_1.1.5         affy_1.48.0           RCurl_1.95-4.8        lazyeval_0.2.0       
[53] munsell_0.4.3         doParallel_1.0.10     rjson_0.2.15          vsn_3.38.0           
[57] affyio_1.40.0        
```

Everything works fine with rcdk 3.4.3 ...

**Comment by sneumann** [comment]
The error message I get above in https://github.com/MassBank/RMassBank/issues/199#issuecomment-408120144 
is coming from https://github.com/cdk/cdk/blob/master/legacy/src/main/java/org/openscience/cdk/formula/MassToFormulaTool.java#L258
Still no idea what changed in the last CDKs relevant to us. Yours, Steffen

**Comment by rajarshi** [comment]
I think returning an empty list, plus a `warning()` would be more appropriate than throwing an error (which is a pain to handle). Also, this should probably be documented better on the `rcdk` side

**Comment by sneumann** [comment]
So, with RMB fixes in https://github.com/sneumann/RMassBank/commit/93cb1608669dcc659d267e6a28fbd689b07b8587 we get as far as 
```
> ###################################################
> ### code chunk number 22: RMassBank.Rnw:468-469
> ###################################################
> mb <- mbWorkflow(mb, infolist_path="./Narcotics_infolist.csv")
mbWorkflow: Step 1. Gather info from several databases
Error in .jcall(cls, "D", "getTotalExactMass", obj, use.true.class = FALSE) : 
  java.lang.NullPointerException
Calls: mbWorkflow ... get.exact.mass -> get.mass -> .jcall -> .jcheck -> .Call
In addition: Warning message:
In get.exact.mass(mol) :
  This function is deprecated. Consider using get.mass
Execution halted
```
in the vignette, which will likely vanish if rcdk gets the NPEs fixed. 
Yours, Steffen
