### ISSUE TITLE
SP$SAMPLE @ RMassBank?

### ISSUE THREAD

**Issue by Treutler** [MassBank/RMassBank#200]
Hi,

is there any possibility in RMassBank to include SP$SAMPLE fields into MassBank records?
If not, how is this usually done?

In addition: Which subtags are commonly used? In the record format specification there are no subtags specified, but there are examples trying to do this, e.g.
https://massbank.eu/MassBank/jsp/RecordDisplay.jsp?id=ETS00011&dsn=Eawag_Addn

Any suggestions welcome.

Best regards,
Hendrik

**Comment by meowcat** [comment]
SP$SAMPLE is added from the Treutler workflow.
