### ISSUE TITLE
Omit CDK messages

### ISSUE THREAD

**Issue by tsufz** [MassBank/RMassBank#202]
Hi, I get lots of cdk messages such as  [main] Info org.openscience.cdk.formula.MassToFormulaTool. Would it be possible to omit those messages?

**Comment by schymane** [comment]
This is an rcdk issue and is resolved in latest versions - you can get around this by using either earlier or newer versions of rcdk. Closing this for now as it is resolved, but we have another issue with rcdk upgrades going in another issue.
