### ISSUE TITLE
Consistency and correctness in filterMultiplicity

### ISSUE THREAD

**Issue by meowcat** [MassBank/RMassBank#219]
Hi,

because I am bringing my s4power branch up to date, I have noticed a possible inconsistency in how `filterMultiplicity` handles masses with multiple possible formulas. I will try to make a minimal reproducible example, but it's a bit tedious. 

When there are multiple formulas with the same multiplicity (which is also the highest multiplicity for that mass), and `recalcBest` is active, the best formula (lowest ppm) is recalculated from the highest-multiplicity formulas only. This is not necessarily the same formula for all scans (e.g. in scan 1 formula CxHyOz might have lower dppm, whereas in scan 2 formula CxHyNzO might have lower dppm for the "almost same" m/z.

The multiplicity (across all scans) is then *recalculated* using only the best match, and there are cases where one formula gets multiplicity 1 (it is the better-ppm formula in only one spectrum) and the peak is dropped.

In the reimplementation in the S4power branch, this is not the case (unless, as now, I specifically enforce this to obtain records identical to the old version). It only assigns the best-multiplicity formula to a mass, but keeps all formulas to recalculate multiplicities.

For now this is posted as an info, since I first want to figure all things out, but the question is:
* do we want to keep this behavior?
* if not, is it sufficient if we wait for the S4power version to be merged into master?
* or should we enforce the possibility to produce identical records with any new version, regardless whether we think it's "wrong"? I could provide a switch, if necessary.

(I am now 2 peaks away from producing records identical to RMassBank 2.3.1 for the 70-pesticide original dataset. Note that 2.3.1 has a couple of minor problems. E.g. I think currently all reanalyzed peaks are just dropped.)

**Comment by tsufz** [comment]
fixed in PR #231
