### ISSUE TITLE
Inclusion of additional adducts

### ISSUE THREAD

**Issue by raalizadeh** [MassBank/RMassBank#233]
Hello guys. 
I am wondering if RMassBank can be updated/used in a way to include additional adducts info (for instance acetate adduct for neg mode) for processing. I am also attaching an R script which includes these adducts info and calculations.
[checkall_adducts.zip](https://github.com/MassBank/RMassBank/files/4464556/checkall_adducts.zip)
Thanks,
Reza

**Comment by meowcat** [comment]
Hi Reza,

sorry for answering late. Somehow went under.
Have you checked the current github master? (`install_github("MassBank/RMassBank")`) It has a large number of adducts available. It also has other modifications, and if you could test that your workflows still work with it, it would help me tremendously :)
```
RMassBank::getAdductInformation("")
```

**Comment by meowcat** [comment]
I believe all of this is in the treutler branch, so closing. Still cf. #244
