### ISSUE TITLE
unable to find an inherited method for function `cleanElnoise`

### ISSUE THREAD

**Issue by korseby** [MassBank/RMassBank#239]
Hi,

(also referring @sneumann @meier-rene here)

I am currently trying to convert MSP spectra to MassBank records.

In the repo `https://github.com/korseby/RMassBank_mFam` running the script `msp2massbank.r` [probably in the function `runContributorToMassBankWorkflow` the call](https://github.com/korseby/RMassBank_mFam/blob/e4f36ccb2b08bfc50b0952087b364b883a4a89fa/galaxy/msp2massbank.r#L2191) 

```R
msmsList <- msmsWorkflow(w = msmsList, mode = ionMode, steps = c(2,3,6,7,8), archivename = runId, newRecalibration = FALSE)
```

returns the following error message:

```R
msmsWorkflow: Step 3. Aggregate all spectra
msmsWorkflow: Step 6. Aggregate recalibrated results
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function �cleanElnoise� for signature �"RmbSpectraSet", "NULL", "numeric"�
Calls: runContributorToMassBankWorkflow ... lapply -> lapply -> lapply -> lapply -> FUN -> <Anonymous>
In addition: Warning messages:
1: In loadRmbSettings(file_or_list = fileSettings_parts[[partIdx]]) :
  Your settings are outdated. Missing will be replaced by default values.
2: In updateSettings(o) :
  Your settings are outdated! The following fields were taken from default values: include_sp_tags
```

Maybe you have an idea?

**Comment by meowcat** [comment]
Hi,

I am not overly familiar with the MetFamily usage of RMassBank, but it seems strange to skip steps there. It seems like you want to skip recalibration. For this you could just set 
```
recalibrator:
    MS1: recalibrate.identity
    MS2: recalibrate.identity
```
in the settings file.
On the other hand, the workflow probably works for the original mFam repo, so I could look into it if that doesn't resolve the problem...

**Comment by korseby** [comment]
More particularly, it works with the [treutler-merge branch](https://github.com/MassBank/RMassBank/tree/treutler-merge). I reverted to that branch temporarily. The latest main branch also throws some errors like masses like 613 are too high. Any other checks that I need to be aware of?
