### ISSUE TITLE
Bug with Boron DBE value

### ISSUE THREAD

**Issue by lauperbe** [MassBank/RMassBank#281]
Hello

there is a bug when processing a boron containing compound.
During step 2 of the msmsWorkflow the DBE calculation crashes with the error below (see attached MWE for Triisopropanolamine borate; C9H18BNO3; https://www.tcichemicals.com/IE/en/p/T2943):

After checking the source code I found that the list used for DBE calculation does not contain an entry for boron:
(Function «analyzeTandemShot» Row 80)

atomDBE <- list(C = 1, N = 1.5, O = 0, Si = 1, H = -0.5, 
        F = -0.5, Cl = -0.5, Br = -0.5, S = 2, Se = 2, P = 1.5, 
        I = -0.5, As = 2.5, Hg = 0, Li = -0.5, Na = -0.5, K = -0.5)

which leads to the atomDBE below, which triggers the error.

Browse[1]> atomDBEs
$C
[1] 2
$B
numeric(0)
$O
[1] 1
$H
[1] 0.5

Would it be possible to include a DBE value for boron in the package?
based on the Qualbrowser boron has a DBE of 0.5. 

Thanks in advance

Benedikt
[MWE_boron.zip](https://github.com/MassBank/RMassBank/files/6108373/MWE_boron.zip)

**Comment by sneumann** [comment]
Thanks for hunting this down ! 
We can either do that for you, or (much cooler!) you go to 
https://github.com/MassBank/RMassBank/blob/dev/R/formulaCalculator.R#L168
hit the edit (Pencil) button in the upper right corner of the file content, add Boron as suggested above 
and this way create a Pull Request (There are more complicated ways to create a PR,
but for such a smallish thing the direct edit in the GitHub editor is the easiest).
Bonus points if you add some more you think you could likely encounter in the future.

Yours, 
Steffen

**Comment by lauperbe** [comment]
Hei Steffen

Thanks for the quick reply.
I did the pull request and included B, Al, Ga and Ca. The DBE values come from Thermo Qualbrowser and might need to be tested.
If I want to use the updated version for processing, can I somehow import the patch 1 directly into R? Sorry for the question but I am not used to GitHub.
Thanks
Benedikt
