### ISSUE TITLE
Replace calls to do.tpying

### ISSUE THREAD

**Issue by pstahlhofen** [MassBank/RMassBank#303]
The `rcdk`-function `do.typing`  is deprecated now. In the documentation it says: `'do.typing' now a synonym for 'set.atom.types'`. I'm not quite sure if this was recently **made** synonym with some potentially new side-effects or if this has been synonym for some time now and we can safely replace it with `set.atom.types`.

**Comment by meowcat** [comment]
In the docs it seems like it merely uses another call convention. I'll just substitute it
https://github.com/CDK-R/cdkr/commit/5a5ec549c71ffc1f2db72243b50193fcab414122#diff-a286238791a97e1f4861216e4132926ddf49011770c74e971740d68fdd972769

https://github.com/CDK-R/cdkr/commit/5a5ec549c71ffc1f2db72243b50193fcab414122#diff-6bd510a238cc4004153b382944f8298ef90c027ce608f88d597709dd6e5d51a9
