### ISSUE TITLE
Please implement the new accession scheme in RMassBank

### ISSUE THREAD

**Issue by meier-rene** [MassBank/RMassBank#315]
Hi,
that's just a heads up, the new accession scheme as discussed in MassBank/MassBank-data#84 is implemented in a separate branch on MassBank-data and MassBank-web. The branches are called upload-rest: New record format description is available: https://github.com/MassBank/MassBank-web/blob/upload-rest/Documentation/MassBankRecordFormat.md#211-accession
I would appreciate if RMassBank could also implement that change.
Yours, Rene

**Comment by meowcat** [comment]
Right now, I am not enforcing the existence of `contributor_prefix` in the settings. In principle, when we require a `contributor_prefix` this will be a breaking change so we should update the main version number?

**Comment by meowcat** [comment]
Hm, maybe for this case there could be a blanket "NFDI" contributor for users who think that they will only contribute a few records? Users who later realize they are bigger players could still migrate their records out to their own contributor ID.

**Comment by tsufz** [comment]
Works
