### ISSUE TITLE
Additional first column in infolist.csv

### ISSUE THREAD

**Issue by tsufz** [MassBank/RMassBank#339]
In the `infolist.csv` always occurs a first column without a column name. I guess this is an exporting artefact due to incorrect written export comments. It may be the index, written by "write.csv()". So, a factorisation to tidy commands is required.

**Comment by schymane** [comment]
sounds like it needs a `row.names=FALSE` upon export ...

**Comment by tsufz** [comment]
Yes, it is. Michele and I suggest to refactorize to tidyverse anyway, doesn't have those problems and is much faster.

**Comment by tsufz** [comment]
Solved in 8fac502960536eb7fc319811de9d21e070252890
