### ISSUE TITLE
Add a hash of arbitrary record info to accessionBuilder

### ISSUE THREAD

**Issue by meowcat** [MassBank/RMassBank#344]
We already have `info("...")` which copies arbitrary metadata into the accession tag. Add `info_hash("...", digits = 3)` to get this as a fixed-width code.

**Comment by tsufz** [comment]
Okay, will try this. I guess, I need to add this to the settings?

**Comment by meowcat** [comment]
Oh I was going to do this rightaway except if you're in the flow :)

**Comment by tsufz** [comment]
No rush, I can run the [M+H] first, but it says that the information comes from AC$ or CH$, but for example, the ion is in MS$?

**Comment by meowcat** [comment]
Hi, this is independent of your other request, we need info("AUTHORS") since we will have the same compound measured by different groups...

**Comment by meowcat** [comment]
Uff, I see that `info()` is pulling from `variables$metadata` rather than `spectrum@info` as I thought (but this matches the documentation in `RMB_options.ini`). I guess I will just fill up the metadata with more values?

**Comment by meowcat** [comment]
Done in #346
