### ISSUE TITLE
Is cactus service deprecated?

### ISSUE THREAD

**Issue by tsufz** [MassBank/RMassBank#347]
Hi @schymane, is the CACTUS service down or deprecated? I write a workaround to pull `InChIKey` using `ChemmineR`.

**Comment by schymane** [comment]
Seems to be working fine for me, tried the test example and a few different SMILES ... (here just one example)

https://cactus.nci.nih.gov/chemical/structure

https://cactus.nci.nih.gov/chemical/structure/CCNC1=NC(=NC(=N1)Cl)NC(C)C/stdinchikey

![image](https://github.com/MassBank/RMassBank/assets/4070141/94e47163-e326-4f3e-8fdc-75fcafe8cf42)

**Comment by tsufz** [comment]
Well, thanks, works now for me as well. So, I add a catch function to send a PUG request if Cactus is down.

**Comment by tsufz** [comment]
Okay, the problem was a lazy call of `getcactus()`....

**Comment by tsufz** [comment]
Fixed in 0ff83bcfae5eb120b1627ee3afdae0a4a3e88259
