### ISSUE TITLE
Integration of US EPA API for data retrieval

### ISSUE THREAD

**Issue by tsufz** [MassBank/RMassBank#350]
The [US EPA API](https://api-ccte.epa.gov/docs/) is back again. We should add a webinterface to retrieve DTXSID on the fly. However, requires a personal API key. I guess, for public institutions, it should be no problem to retrieve it.

**Comment by tsufz** [comment]
- [  ] add basic API interface
- [  ] add retrieval by InChIKey
- [  ] if key failes, fall back to CAS
- [  ] add key entry to settings

**Comment by ChemConnector** [comment]
Contact ***@***.*** and he will Give you a keyOn Aug 14, 2023, at 11:35 PM, Tobias Schulze ***@***.***> wrote:﻿

[  ] add basic API interface
[  ] add retrieval by InChIKey
[  ] if key failes, fall back to CAS
[  ] add key entry to settings

**Comment by tsufz** [comment]
@ChemConnector, I got a private key. I guess, this is not the purpose of a key to distribute it publicly?

Cheers,
Tobi

**Comment by tsufz** [comment]
Skip the CAS request so far.

**Comment by tsufz** [comment]
Solved in https://github.com/MassBank/RMassBank/pull/342/commits/cc4f10208e07fe876822d9ae211d32430fbd0900
