### ISSUE TITLE
Suppress 50 or more warnings message at end of msmsWorkflow

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#36]
_Issue by **[schymane](https://github.com/schymane)** from Monday Oct 28, 2013 at 13:01 GMT_
_Originally opened as https://github.com/sneumann/RMassBank/issues/28_

----

**Comment by schymane** [comment]
Michele, can we close this now?

**Comment by meowcat** [comment]
I fixed at least two of the warning generating steps (0e6303 to 7f80a2d), Closing for now, reopen if still something comes up
