### ISSUE TITLE
Direct Infusion Data

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#38]
_Issue by **[schymane](https://github.com/schymane)** from Monday Oct 28, 2013 at 13:11 GMT_
_Originally opened as https://github.com/sneumann/RMassBank/issues/30_

----

adjust mzR to live without precursor scans (MS1). E.g. IPB or UJI MS/MS. Have to give exact RT, then should work

**Comment by schymane** [comment]
Erik, can you see if this has happened? This is related to the dataset from 7 April too.

**Comment by schymane** [comment]
Original cause of issue is fixed with fillPrecursorScan. This is now about direct infusion data

**Comment by tsufz** [comment]
We stopped to do direct infusion analysis in order of the problems to receive MS with newer RMB versions (worked quite well with 0.1 ;-)), but were also quite dirty and sometimes fancy...

**Comment by meowcat** [comment]
closed for now. Can be reopened in case the necessity would arise
