### ISSUE TITLE
Test mzR on dynamic exclusion data (ABSciex)

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#39]
_Issue by **[schymane](https://github.com/schymane)** from Monday Oct 28, 2013 at 13:14 GMT_
_Originally opened as https://github.com/sneumann/RMassBank/issues/31_

---

Test mzR to cover data dependent with dynamic exclusion where no peak exists for xcms. E.g. BfG ABSciex data. Have possible additional problem of accuracy?

**Comment by schymane** [comment]
@ermueller This could be an interesting test case for fillPrecursorScan=TRUE, correct?
This was also that additional dataset we talked about today.

**Comment by meowcat** [comment]
@schymane @sneumann Do we have data? Does it work?

**Comment by schymane** [comment]
Maybe we had data back in 2015 ... I don't have any available now and this comment is so old things have moved on. We're testing out ABSciex data elsewhere atm - I think we can close this for now and reopen a new one if relevant.
