### ISSUE TITLE
Test mzR and xcms workflows on low res data

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#41]
_Issue by **[schymane](https://github.com/schymane)** from Monday Oct 28, 2013 at 13:31 GMT_
_Originally opened as https://github.com/sneumann/RMassBank/issues/33_

---

**Comment by meowcat** [comment]
Doesn't make sense to me for now, I also don't see use cases. Agree @schymane @tsufz ?

**Comment by tsufz** [comment]
I think this was related to the old question if we could also add low res data. Let's close it.
