### ISSUE TITLE
Simplify the data structure of msmsWorkspace?

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#47]
_Issue by **[meowcat](https://github.com/meowcat)** from Friday Nov 01, 2013 at 10:42 GMT_
_Originally opened as https://github.com/sneumann/RMassBank/issues/39_

----

One problem with RMassBank is that I feel I am probably the only person who actually understands the whole data structure in the msmsWorkspace object, which has become quite complex and branched. This happened because it grew "organically" and I just stuck new stuff in wherever I needed it. I would like to refactor this if I get some support with the structure planning. I feel this sounds like more work than it actually will be. Thoughts?

Ideally one would, of course, S4ize everything (classes for every slot type), but I am too unversed in S4 to do this efficiently and also probably don't have the time.

Another thing one could do is to use the MSnbase Spectrum, Spectrum1, Spectrum2 classes or extensions thereof to store spectra. I didn't understand the purpose of that package until I was nearly done with RMassBank, which is why I haven't used it...

**Comment by meowcat** [comment]
Check out the refactoring branch. It currently depends on MSnbase. If we really want to isolate out the Spectrum class from there, we can do it... I am currently happy with the MSnbase dependency but we can sort this out once we see if we are happy with the refactoring or not.
