### ISSUE TITLE
Catch & fix case where scan acquisition & settings file mismatch

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#52]
_Issue by **[schymane](https://github.com/schymane)** from Friday Jan 10, 2014 at 10:34 GMT_
_Originally opened as https://github.com/sneumann/RMassBank/issues/44_

---

e.g. 14 scans in settings file, but only 13 scans recorded.
Examples 231, 2898. Michele is onto it.

**Comment by schymane** [comment]
Look into this after BioC release - it's a useability problem not a bug as this is user error

**Comment by meowcat** [comment]
This gives warnings in the current version, so seems OK
