### ISSUE TITLE
MS1, MS2 and Plotting functions into RMassBankExtras

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#65]
@meowcat: Should we get the MS1, MS2 and plotting functionality we seem to be using more and more actually into RMassBankExtras, rather than having scripts floating around?
My current input is only mz, RT, I do play with RT, mz error windows and the cut-off but not much else, the plotting may need a bit of playing with to work but not too dramatic.
What do you think?

**Comment by meowcat** [comment]
I believe this stuff is now in your own packages...
