### ISSUE TITLE
missing drop=FALSE somewhere

### ISSUE THREAD

**Issue by sneumann** [MassBank/RMassBank#72]
If a spectrum contains only a single peak, 
at step=8 in the workflow there is 

```
Error in if (nrow(peaks) == 0) { : argument is of length zero
```

**Comment by ermueller** [comment]
Error message in 38cab82908345d764e402e827670fd113c058bd0
Made message more understandable in 19e356bb53e4692e3296cd19c79ec8c92c303c07

**Comment by sneumann** [comment]
So we now fail with a proper error message. Even better would be to handle the cause properly, 
and continue with an (empty) spectrum.

For a proper unitTest, we'd need an example with peaklist import, one single peak that will get filtered at stage 5 (assigning formula to recalibrated peaks) or stage 6 (aggregating).

**Comment by schymane** [comment]
Material for a unit test sent to Erik 21.1.2015

**Comment by schymane** [comment]
Add workspace to RMB Data, see #116

**Comment by ermueller** [comment]
Unit test has been added a while ago,but now unit tests automatically happen while R CMD check runs
