### ISSUE TITLE
Adjust addPeaks to work with ;s in csv

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#74]
Parallel to the fix for loadList, thanks...

**Comment by schymane** [comment]
another closed issue coming back to haunt us?
I just ran into problems with loadInfolists and addPeaks with ;-separated csvs again - which worked fine if I saved the csvs as ,-separated.
InfoList:
Error in read.table( ....) - more columns than column names
addPeaks:
Error in round(spec_add_peaks$mzFound, 4) : non-numeric argument to mathematical function.

So, where did this fix go missing?

RMassBank_1.9.5.2 from 23.03.2015 16:23.

**Comment by ermueller** [comment]
It's still in there, and it works when I do it. 

Can you send me the infolist?

**Comment by schymane** [comment]
I’ll send you the files by email, thx

**Comment by schymane** [comment]
just to follow up
(a) Erik tried a fix but it resulted in a different error message, I emailed separately
[...I fixed a thing in addPeaks, which very likely resulted in "NAs" being read wrong ...]
(b) I can recreate exactly the same error on the 1.9.6 committed to BioC, so it's probably not a merging issue but rather a special case with strange data.
mbWorkflow: Step 4. Spectra compilation
Compiling: 150213_05.mzML
Compiling: 150213_06.mzML
Compiling: 150213_07.mzML
Error in round(spec_add_peaks$mzFound, 4) : 
  non-numeric argument to mathematical function

> sessionInfo()
R Under development (unstable) (2014-06-23 r66008)
Platform: x86_64-w64-mingw32/x64 (64-bit)
other attached packages:
 [1] Hmisc_3.14-4      Formula_1.1-1     survival_2.37-7   lattice_0.20-29   mzR_1.11.0       
 [6] rcdk_3.2.3.2      fingerprint_3.5.2 RMassBank_1.9.6   Rcpp_0.11.2       rJava_0.9-6

**Comment by ermueller** [comment]
Is fixed, but not yet pushed to my github. Sorry, didn't think straight when adding the label.
