### ISSUE TITLE
Move RMassBank to new MB repository

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#86]
https://github.com/MassBank/
Related: add more info to github MassBank? Looks very empty, no people, just one converter at the moment.

**Comment by schymane** [comment]
Question is whether we add new labels now, or port first, then add new labels

**Comment by sneumann** [comment]
How to move a repo:
https://help.github.com/articles/transferring-a-repository/

**Comment by uchem-massbank** [comment]
Erik needs to be a member of MassBank before we can transfer.
@sneumann: can you invite him?

**Comment by meowcat** [comment]
The repo is now in the MassBank organization.
The old URLs should still work for pushing and pulling (according to documentation) but it's probably a good idea to link your local Git repos to the new url (MassBank instead of meowcat in the URL).
