### ISSUE TITLE
catch CTS failures

### ISSUE THREAD

**Issue by schymane** [MassBank/RMassBank#88]
see Metabolights records

**Comment by ermueller** [comment]
Tentatively added timeout error message in dde318f5b3a22fa4d38e4a1ecc2d808e391abf72

**Comment by ermueller** [comment]
Also, I made the CTS stuff in the examples not run anymore, so I can at least R CMD check the other stuff properly.

**Comment by sneumann** [comment]
"CTS stuff in the examples not run anymore" 
Should be reverted, as it quickly catches CTS failures, so UCDavies gets emails earlier.

**Comment by schymane** [comment]
Instead try warnings and see if we can get build warnings rather than build errors

**Comment by schymane** [comment]
Isn't this resolved? If so, add "to close on merging" label?

**Comment by ermueller** [comment]
Yeh, this is basically resolved by fixing gatherData altogether.
